/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID 2fc100090fc7)
#  Generated on:      Fri Apr 20 12:38:36 2018
#  Design:            BlackJack_top
#  Command:           saveNetlist FINAL/NETLIST/BlackJack_top_final.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID 05b2a4f075ed)
#  Generated on:      Thu Apr 19 09:48:26 2018
#  Design:            BlackJack_top
#  Command:           saveDesign DB/BlackJack_encounter.enc
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : M-2016.12
// Date      : Thu Apr 19 08:05:29 2018
/////////////////////////////////////////////////////////////
module BlackJack_top (
	cardReady, 
	cardValue, 
	clk, 
	start, 
	lost, 
	finished, 
	newCard, 
	score);
   input cardReady;
   input [3:0] cardValue;
   input clk;
   input start;
   output lost;
   output finished;
   output newCard;
   output [4:0] score;

   // Internal wires
   wire FE_PHN524_core_I_1_regLoad_2_;
   wire FE_PHN523_FE_OFN1_s_start;
   wire FE_PHN522_s_score_4_;
   wire FE_PHN521_FE_OFN0_s_cardReady;
   wire FE_PHN520_n56;
   wire FE_PHN519_n62;
   wire FE_PHN518_n93;
   wire FE_PHN517_n60;
   wire FE_PHN516_FE_OFN1_s_start;
   wire FE_PHN515_core_I_2_cardReadySync;
   wire FE_PHN514_n60;
   wire FE_PHN513_FE_OFN5_s_cardValue_0_;
   wire FE_PHN512_FE_OFN4_s_cardValue_1_;
   wire FE_PHN511_n93;
   wire FE_PHN510_s_score_1_;
   wire FE_PHN509_s_score_3_;
   wire FE_PHN508_s_score_2_;
   wire FE_PHN507_n56;
   wire FE_PHN506_FE_OFN0_s_cardReady;
   wire FE_PHN505_s_score_4_;
   wire FE_PHN504_s_score_0_;
   wire FE_PHN503_n62;
   wire FE_PHN502_FE_OFN1_s_start;
   wire FE_PHN501_n93;
   wire FE_PHN500_core_I_1_regLoad_3_;
   wire FE_PHN499_n60;
   wire FE_PHN498_FE_OFN0_s_cardReady;
   wire FE_PHN497_s_score_0_;
   wire FE_PHN496_s_score_4_;
   wire FE_PHN495_n56;
   wire FE_PHN494_n62;
   wire FE_PHN493_FE_OFN1_s_start;
   wire FE_PHN492_s_score_1_;
   wire FE_PHN491_FE_OFN5_s_cardValue_0_;
   wire FE_PHN490_FE_OFN4_s_cardValue_1_;
   wire FE_PHN489_n59;
   wire FE_PHN488_s_score_3_;
   wire FE_PHN487_FE_OFN2_s_cardValue_3_;
   wire FE_PHN486_s_score_2_;
   wire FE_PHN485_core_I_2_cardReadySync;
   wire FE_PHN484_core_I_1_regLoad_2_;
   wire FE_PHN483_s_score_4_;
   wire FE_PHN482_FE_OFN3_s_cardValue_2_;
   wire FE_PHN481_n62;
   wire FE_PHN480_FE_OFN0_s_cardReady;
   wire FE_PHN479_n56;
   wire FE_PHN478_s_score_1_;
   wire FE_PHN477_FE_OFN2_s_cardValue_3_;
   wire FE_PHN476_s_score_3_;
   wire FE_PHN475_FE_OFN5_s_cardValue_0_;
   wire FE_PHN474_s_score_0_;
   wire FE_PHN473_s_score_2_;
   wire FE_PHN472_FE_OFN4_s_cardValue_1_;
   wire FE_PHN471_FE_OFN1_s_start;
   wire FE_PHN470_core_I_1_regLoad_4_;
   wire FE_PHN469_core_I_1_regLoad_3_;
   wire FE_PHN468_core_I_2_cardReadySync;
   wire FE_PHN467_s_score_2_;
   wire FE_PHN466_FE_OFN3_s_cardValue_2_;
   wire FE_PHN465_s_score_0_;
   wire FE_PHN464_n62;
   wire FE_PHN463_s_score_4_;
   wire FE_PHN462_FE_OFN0_s_cardReady;
   wire FE_PHN461_n56;
   wire FE_PHN460_n59;
   wire FE_PHN459_FE_OFN5_s_cardValue_0_;
   wire FE_PHN458_FE_OFN4_s_cardValue_1_;
   wire FE_PHN457_s_score_3_;
   wire FE_PHN456_s_score_1_;
   wire FE_PHN455_FE_OFN1_s_start;
   wire FE_PHN454_core_I_1_regLoad_4_;
   wire FE_PHN453_core_I_1_regLoad_3_;
   wire FE_PHN452_core_I_1_regLoad_2_;
   wire FE_PHN451_core_I_2_cardReadySync;
   wire FE_PHN450_s_score_0_;
   wire FE_PHN449_s_score_4_;
   wire FE_PHN448_FE_OFN3_s_cardValue_2_;
   wire FE_PHN447_n62;
   wire FE_PHN446_FE_OFN0_s_cardReady;
   wire FE_PHN445_n56;
   wire FE_PHN444_FE_OFN2_s_cardValue_3_;
   wire FE_PHN443_FE_OFN5_s_cardValue_0_;
   wire FE_PHN442_FE_OFN4_s_cardValue_1_;
   wire FE_PHN441_s_score_3_;
   wire FE_PHN440_s_score_1_;
   wire FE_PHN439_s_score_2_;
   wire FE_PHN438_core_I_1_regLoad_2_;
   wire FE_PHN437_FE_OFN1_s_start;
   wire FE_PHN436_core_I_1_regLoad_4_;
   wire FE_PHN435_core_I_1_regLoad_3_;
   wire FE_PHN434_core_I_2_cardReadySync;
   wire FE_PHN433_s_score_4_;
   wire FE_PHN432_FE_OFN0_s_cardReady;
   wire FE_PHN431_n62;
   wire FE_PHN430_FE_OFN3_s_cardValue_2_;
   wire FE_PHN429_n56;
   wire FE_PHN428_s_score_1_;
   wire FE_PHN427_FE_OFN2_s_cardValue_3_;
   wire FE_PHN426_FE_OFN4_s_cardValue_1_;
   wire FE_PHN425_FE_OFN5_s_cardValue_0_;
   wire FE_PHN424_s_score_3_;
   wire FE_PHN423_s_score_2_;
   wire FE_PHN422_s_score_0_;
   wire FE_PHN421_core_I_1_regLoad_2_;
   wire FE_PHN420_FE_OFN1_s_start;
   wire FE_PHN419_core_I_1_regLoad_4_;
   wire FE_PHN418_core_I_1_regLoad_3_;
   wire FE_PHN417_core_I_2_cardReadySync;
   wire FE_PHN416_s_score_2_;
   wire FE_PHN415_s_score_3_;
   wire FE_PHN414_s_score_4_;
   wire FE_PHN413_n56;
   wire FE_PHN412_FE_OFN3_s_cardValue_2_;
   wire FE_PHN411_s_score_0_;
   wire FE_PHN410_FE_OFN0_s_cardReady;
   wire FE_PHN409_n62;
   wire FE_PHN408_FE_OFN2_s_cardValue_3_;
   wire FE_PHN407_FE_OFN5_s_cardValue_0_;
   wire FE_PHN406_FE_OFN4_s_cardValue_1_;
   wire FE_PHN405_s_score_1_;
   wire FE_PHN404_core_I_1_regLoad_4_;
   wire FE_PHN403_FE_OFN1_s_start;
   wire FE_PHN402_core_I_1_regLoad_3_;
   wire FE_PHN401_core_I_1_regLoad_2_;
   wire FE_PHN400_core_I_2_cardReadySync;
   wire FE_PHN399_s_score_2_;
   wire FE_PHN398_s_score_3_;
   wire FE_PHN397_FE_OFN3_s_cardValue_2_;
   wire FE_PHN396_FE_OFN0_s_cardReady;
   wire FE_PHN395_n62;
   wire FE_PHN394_n56;
   wire FE_PHN393_FE_OFN4_s_cardValue_1_;
   wire FE_PHN392_FE_OFN2_s_cardValue_3_;
   wire FE_PHN391_FE_OFN5_s_cardValue_0_;
   wire FE_PHN390_s_score_0_;
   wire FE_PHN389_s_score_1_;
   wire FE_PHN388_n49;
   wire FE_PHN387_n53;
   wire FE_PHN386_n88;
   wire FE_PHN385_core_I_2_cardReadySync;
   wire FE_PHN384_core_I_1_regLoad_4_;
   wire FE_PHN383_FE_OFN1_s_start;
   wire FE_PHN382_core_I_1_regLoad_3_;
   wire FE_PHN381_core_I_1_regLoad_2_;
   wire FE_PHN380_FE_OFN3_s_cardValue_2_;
   wire FE_PHN379_FE_OFN2_s_cardValue_3_;
   wire FE_PHN378_FE_OFN4_s_cardValue_1_;
   wire FE_PHN377_FE_OFN5_s_cardValue_0_;
   wire FE_PHN376_s_score_0_;
   wire FE_PHN375_n88;
   wire FE_PHN374_FE_OFN0_s_cardReady;
   wire FE_PHN373_n51;
   wire FE_PHN372_n49;
   wire FE_PHN371_n50;
   wire FE_PHN370_n64;
   wire FE_PHN369_n56;
   wire FE_PHN368_n62;
   wire FE_PHN367_core_I_2_cardReadySync;
   wire FE_PHN366_core_I_1_regLoad_4_;
   wire FE_PHN365_n53;
   wire FE_PHN364_n54;
   wire FE_PHN363_s_score_1_;
   wire FE_PHN362_n65;
   wire FE_PHN361_n66;
   wire FE_PHN360_core_I_1_regLoad_2_;
   wire FE_PHN359_n55;
   wire FE_PHN358_core_I_1_regLoad_3_;
   wire FE_PHN357_FE_OFN1_s_start;
   wire FE_PHN356_n88;
   wire FE_PHN355_FE_OFN3_s_cardValue_2_;
   wire FE_PHN354_FE_OFN5_s_cardValue_0_;
   wire FE_PHN353_FE_OFN4_s_cardValue_1_;
   wire FE_PHN352_FE_OFN2_s_cardValue_3_;
   wire FE_PHN351_n56;
   wire FE_PHN350_n62;
   wire FE_PHN349_s_score_0_;
   wire FE_PHN348_s_score_1_;
   wire FE_PHN347_n51;
   wire FE_PHN346_n49;
   wire FE_PHN345_n50;
   wire FE_PHN344_FE_OFN0_s_cardReady;
   wire FE_PHN343_n54;
   wire FE_PHN342_n64;
   wire FE_PHN341_n55;
   wire FE_PHN340_n66;
   wire FE_PHN339_n65;
   wire FE_PHN338_n53;
   wire FE_PHN337_core_I_1_regLoad_2_;
   wire FE_PHN336_core_I_1_regLoad_3_;
   wire FE_PHN335_core_I_1_regLoad_4_;
   wire FE_PHN334_FE_OFN1_s_start;
   wire FE_PHN333_core_I_1_regAdd_4_;
   wire FE_PHN332_core_I_1_regAdd_3_;
   wire FE_PHN331_n48;
   wire FE_PHN330_n54;
   wire FE_PHN329_n50;
   wire FE_PHN328_n53;
   wire FE_PHN327_n59;
   wire FE_PHN326_n49;
   wire FE_PHN325_n65;
   wire FE_PHN324_FE_OFN0_s_cardReady;
   wire FE_PHN323_n58;
   wire FE_PHN322_n60;
   wire FE_PHN321_n64;
   wire FE_PHN320_n55;
   wire FE_PHN319_n66;
   wire FE_PHN318_n57;
   wire FE_PHN317_n61;
   wire FE_PHN316_n63;
   wire FE_PHN315_n52;
   wire FE_PHN314_n51;
   wire FE_PHN313_FE_OFN1_s_start;
   wire FE_PHN312_core_I_1_regAdd_1_;
   wire FE_PHN311_core_I_1_regAdd_0_;
   wire FE_PHN310_core_I_1_regLoad_0_;
   wire FE_PHN309_core_I_1_regLoad_1_;
   wire FE_PHN308_core_I_2_state_3_;
   wire FE_PHN307_core_I_2_state_1_;
   wire FE_PHN306_core_I_2_state_0_;
   wire FE_PHN305_core_I_2_state_2_;
   wire FE_PHN304_n59;
   wire FE_PHN303_FE_OFN0_s_cardReady;
   wire FE_PHN302_n49;
   wire FE_PHN301_n52;
   wire FE_PHN300_n53;
   wire FE_PHN299_n65;
   wire FE_PHN298_n64;
   wire FE_PHN297_n60;
   wire FE_PHN296_n50;
   wire FE_PHN295_n58;
   wire FE_PHN294_n66;
   wire FE_PHN293_n63;
   wire FE_PHN292_n61;
   wire FE_PHN291_n51;
   wire FE_PHN290_n54;
   wire FE_PHN289_n48;
   wire FE_PHN288_n57;
   wire FE_PHN287_n55;
   wire FE_PHN286_FE_OFN1_s_start;
   wire FE_PHN285_core_I_1_regAdd_1_;
   wire FE_PHN284_core_I_1_regLoad_0_;
   wire FE_PHN283_core_I_1_regAdd_0_;
   wire FE_PHN282_core_I_2_state_1_;
   wire FE_PHN281_core_I_1_regLoad_1_;
   wire FE_PHN280_core_I_2_state_3_;
   wire FE_PHN279_core_I_2_state_2_;
   wire FE_PHN278_core_I_2_state_0_;
   wire FE_PHN277_FE_OFN0_s_cardReady;
   wire FE_PHN276_n51;
   wire FE_PHN275_n53;
   wire FE_PHN274_n58;
   wire FE_PHN273_n60;
   wire FE_PHN272_n49;
   wire FE_PHN271_n59;
   wire FE_PHN270_n64;
   wire FE_PHN269_n57;
   wire FE_PHN268_n55;
   wire FE_PHN267_n61;
   wire FE_PHN266_n63;
   wire FE_PHN265_n48;
   wire FE_PHN264_n50;
   wire FE_PHN263_n54;
   wire FE_PHN262_n65;
   wire FE_PHN261_n66;
   wire FE_PHN260_n52;
   wire FE_PHN259_FE_OFN1_s_start;
   wire FE_PHN258_core_I_1_regAdd_1_;
   wire FE_PHN257_core_I_1_regLoad_0_;
   wire FE_PHN256_core_I_1_regAdd_0_;
   wire FE_PHN255_core_I_1_regLoad_1_;
   wire FE_PHN254_core_I_2_state_3_;
   wire FE_PHN253_core_I_2_state_2_;
   wire FE_PHN252_core_I_2_state_0_;
   wire FE_PHN251_core_I_2_state_1_;
   wire FE_PHN250_core_I_1_regAdd_2_;
   wire FE_PHN249_n48;
   wire FE_PHN248_n54;
   wire FE_PHN247_FE_OFN0_s_cardReady;
   wire FE_PHN246_n65;
   wire FE_PHN245_n53;
   wire FE_PHN244_n51;
   wire FE_PHN243_n60;
   wire FE_PHN242_n64;
   wire FE_PHN241_n58;
   wire FE_PHN240_n61;
   wire FE_PHN239_n55;
   wire FE_PHN238_n63;
   wire FE_PHN237_n52;
   wire FE_PHN236_n49;
   wire FE_PHN235_n66;
   wire FE_PHN234_n50;
   wire FE_PHN233_n57;
   wire FE_PHN232_n59;
   wire FE_PHN231_FE_OFN1_s_start;
   wire FE_PHN230_core_I_1_regAdd_1_;
   wire FE_PHN229_core_I_1_regAdd_0_;
   wire FE_PHN228_core_I_1_regLoad_0_;
   wire FE_PHN227_core_I_2_state_3_;
   wire FE_PHN226_core_I_2_state_2_;
   wire FE_PHN225_core_I_2_state_0_;
   wire FE_PHN224_core_I_2_state_1_;
   wire FE_PHN223_core_I_1_regLoad_1_;
   wire FE_PHN222_core_I_1_regAdd_2_;
   wire FE_PHN221_core_I_1_regAdd_3_;
   wire FE_PHN220_n60;
   wire FE_PHN219_n51;
   wire FE_PHN218_n55;
   wire FE_PHN217_n58;
   wire FE_PHN216_n54;
   wire FE_PHN215_FE_OFN0_s_cardReady;
   wire FE_PHN214_n65;
   wire FE_PHN213_n64;
   wire FE_PHN212_n66;
   wire FE_PHN211_n63;
   wire FE_PHN210_n61;
   wire FE_PHN209_n57;
   wire FE_PHN208_n48;
   wire FE_PHN207_n50;
   wire FE_PHN206_n52;
   wire FE_PHN205_n49;
   wire FE_PHN204_n59;
   wire FE_PHN203_n53;
   wire FE_PHN202_FE_OFN1_s_start;
   wire FE_PHN201_core_I_1_regAdd_1_;
   wire FE_PHN200_core_I_1_regLoad_0_;
   wire FE_PHN199_core_I_1_regAdd_0_;
   wire FE_PHN198_core_I_1_regLoad_1_;
   wire FE_PHN197_core_I_2_state_2_;
   wire FE_PHN196_core_I_2_state_3_;
   wire FE_PHN195_core_I_2_state_1_;
   wire FE_PHN194_core_I_2_state_0_;
   wire FE_PHN193_core_I_1_regAdd_4_;
   wire FE_PHN192_core_I_1_regAdd_3_;
   wire FE_PHN191_core_I_1_regAdd_2_;
   wire FE_PHN190_n64;
   wire FE_PHN189_n49;
   wire FE_PHN188_n58;
   wire FE_PHN187_n54;
   wire FE_PHN186_n51;
   wire FE_PHN185_FE_OFN0_s_cardReady;
   wire FE_PHN184_n60;
   wire FE_PHN183_n59;
   wire FE_PHN182_n48;
   wire FE_PHN181_n63;
   wire FE_PHN180_n55;
   wire FE_PHN179_n65;
   wire FE_PHN178_n50;
   wire FE_PHN177_n61;
   wire FE_PHN176_n53;
   wire FE_PHN175_n52;
   wire FE_PHN174_n66;
   wire FE_PHN173_n57;
   wire FE_PHN172_FE_OFN1_s_start;
   wire FE_PHN171_core_I_1_regAdd_1_;
   wire FE_PHN170_core_I_1_regAdd_0_;
   wire FE_PHN169_core_I_1_regLoad_0_;
   wire FE_PHN168_core_I_2_state_2_;
   wire FE_PHN167_core_I_1_regLoad_1_;
   wire FE_PHN166_core_I_2_state_1_;
   wire FE_PHN165_core_I_2_state_3_;
   wire FE_PHN164_core_I_2_state_0_;
   wire FE_PHN163_core_I_1_regAdd_4_;
   wire FE_PHN162_core_I_1_regAdd_3_;
   wire FE_PHN161_core_I_1_regAdd_2_;
   wire FE_PHN160_FE_OFN0_s_cardReady;
   wire FE_PHN159_n48;
   wire FE_PHN158_n49;
   wire FE_PHN157_n65;
   wire FE_PHN156_n50;
   wire FE_PHN155_n51;
   wire FE_PHN154_n59;
   wire FE_PHN153_n64;
   wire FE_PHN152_n53;
   wire FE_PHN151_n58;
   wire FE_PHN150_n60;
   wire FE_PHN149_n61;
   wire FE_PHN148_n57;
   wire FE_PHN147_n66;
   wire FE_PHN146_n55;
   wire FE_PHN145_n52;
   wire FE_PHN144_n63;
   wire FE_PHN143_n54;
   wire FE_PHN142_FE_OFN1_s_start;
   wire FE_PHN141_core_I_1_regAdd_1_;
   wire FE_PHN140_core_I_1_regAdd_0_;
   wire FE_PHN139_core_I_2_state_2_;
   wire FE_PHN138_core_I_1_regLoad_0_;
   wire FE_PHN137_core_I_2_state_0_;
   wire FE_PHN136_core_I_2_state_3_;
   wire FE_PHN135_core_I_2_state_1_;
   wire FE_PHN134_core_I_1_regLoad_1_;
   wire FE_PHN133_core_I_1_regAdd_4_;
   wire FE_PHN132_core_I_1_regAdd_3_;
   wire FE_PHN131_core_I_1_regAdd_2_;
   wire FE_PHN130_n60;
   wire FE_PHN129_n50;
   wire FE_PHN128_n52;
   wire FE_PHN127_n51;
   wire FE_PHN126_n65;
   wire FE_PHN125_n53;
   wire FE_PHN124_n58;
   wire FE_PHN123_n59;
   wire FE_PHN122_n48;
   wire FE_PHN121_FE_OFN0_s_cardReady;
   wire FE_PHN120_n55;
   wire FE_PHN119_n57;
   wire FE_PHN118_n61;
   wire FE_PHN117_n54;
   wire FE_PHN116_n49;
   wire FE_PHN115_n66;
   wire FE_PHN114_n63;
   wire FE_PHN113_n64;
   wire FE_PHN112_FE_OFN1_s_start;
   wire FE_PHN111_core_I_1_regAdd_1_;
   wire FE_PHN110_core_I_2_state_2_;
   wire FE_PHN109_core_I_1_regAdd_0_;
   wire FE_PHN108_core_I_1_regLoad_0_;
   wire FE_PHN107_core_I_2_state_3_;
   wire FE_PHN106_core_I_2_state_1_;
   wire FE_PHN105_core_I_2_state_0_;
   wire FE_PHN104_core_I_1_regLoad_1_;
   wire FE_PHN103_core_I_1_regAdd_4_;
   wire FE_PHN102_core_I_1_regAdd_2_;
   wire FE_PHN101_core_I_1_regAdd_3_;
   wire FE_PHN100_FE_OFN0_s_cardReady;
   wire FE_PHN99_FE_OFN1_s_start;
   wire FE_PHN98_n60;
   wire FE_PHN97_n49;
   wire FE_PHN96_n64;
   wire FE_PHN95_n54;
   wire FE_PHN94_n59;
   wire FE_PHN93_n58;
   wire FE_PHN92_n66;
   wire FE_PHN91_n61;
   wire FE_PHN90_n63;
   wire FE_PHN89_n57;
   wire FE_PHN88_n55;
   wire FE_PHN87_n52;
   wire FE_PHN86_n51;
   wire FE_PHN85_n48;
   wire FE_PHN84_n50;
   wire FE_PHN83_n65;
   wire FE_PHN82_n53;
   wire FE_PHN81_core_I_1_regAdd_1_;
   wire FE_PHN80_core_I_1_regLoad_0_;
   wire FE_PHN79_core_I_1_regAdd_0_;
   wire FE_PHN78_core_I_1_regLoad_1_;
   wire FE_PHN77_core_I_2_state_3_;
   wire FE_PHN76_core_I_2_state_1_;
   wire FE_PHN75_core_I_2_state_2_;
   wire FE_PHN74_core_I_2_state_0_;
   wire FE_PHN73_core_I_1_regAdd_4_;
   wire FE_PHN72_core_I_1_regAdd_3_;
   wire FE_PHN71_core_I_1_regAdd_2_;
   wire FE_PHN70_FE_OFN0_s_cardReady;
   wire FE_PHN69_n60;
   wire FE_PHN68_FE_OFN1_s_start;
   wire FE_PHN67_n59;
   wire FE_PHN66_n48;
   wire FE_PHN65_n51;
   wire FE_PHN64_n65;
   wire FE_PHN63_n53;
   wire FE_PHN62_n49;
   wire FE_PHN61_n58;
   wire FE_PHN60_n64;
   wire FE_PHN59_n61;
   wire FE_PHN58_n52;
   wire FE_PHN57_n63;
   wire FE_PHN56_n66;
   wire FE_PHN55_n54;
   wire FE_PHN54_n50;
   wire FE_PHN53_n57;
   wire FE_PHN52_n55;
   wire FE_PHN51_core_I_1_regAdd_3_;
   wire FE_PHN50_core_I_1_regAdd_0_;
   wire FE_PHN49_core_I_1_regLoad_0_;
   wire FE_PHN48_core_I_1_regLoad_1_;
   wire FE_PHN47_core_I_1_regAdd_1_;
   wire FE_PHN46_core_I_1_regAdd_4_;
   wire FE_PHN45_core_I_1_regAdd_2_;
   wire FE_PHN44_core_I_2_state_1_;
   wire FE_PHN43_core_I_2_state_0_;
   wire FE_PHN42_core_I_2_state_2_;
   wire FE_PHN41_core_I_2_state_3_;
   wire FE_PHN40_n66;
   wire FE_PHN39_n58;
   wire FE_PHN38_FE_OFN0_s_cardReady;
   wire FE_PHN37_n64;
   wire FE_PHN36_n65;
   wire FE_PHN35_n51;
   wire FE_PHN34_n50;
   wire FE_PHN33_n48;
   wire FE_PHN32_n54;
   wire FE_PHN31_n53;
   wire FE_PHN30_n49;
   wire FE_PHN29_n63;
   wire FE_PHN28_n52;
   wire FE_PHN27_n55;
   wire FE_PHN26_n61;
   wire FE_PHN25_n59;
   wire FE_PHN24_n57;
   wire FE_PHN23_FE_OFN1_s_start;
   wire FE_PHN22_core_I_1_regAdd_3_;
   wire FE_PHN21_core_I_1_regLoad_0_;
   wire FE_PHN20_core_I_1_regAdd_0_;
   wire FE_PHN19_core_I_1_regLoad_1_;
   wire FE_PHN18_core_I_2_state_1_;
   wire FE_PHN17_core_I_1_regAdd_4_;
   wire FE_PHN16_core_I_1_regAdd_2_;
   wire FE_PHN15_core_I_1_regAdd_1_;
   wire FE_PHN14_core_I_2_state_0_;
   wire FE_PHN13_core_I_2_state_2_;
   wire FE_PHN12_core_I_2_state_3_;
   wire FE_OFN11_n67;
   wire FE_OFN10_s_score_3_;
   wire FE_OFN9_s_score_4_;
   wire FE_OFN8_s_score_2_;
   wire FE_OFN7_s_score_0_;
   wire FE_OFN6_s_score_1_;
   wire FE_OFN5_s_cardValue_0_;
   wire FE_OFN4_s_cardValue_1_;
   wire FE_OFN3_s_cardValue_2_;
   wire FE_OFN2_s_cardValue_3_;
   wire FE_OFN1_s_start;
   wire FE_OFN0_s_cardReady;
   wire s_cardReady;
   wire s_clk;
   wire s_start;
   wire s_lost;
   wire \core/I_2/cardReadySync ;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire [3:0] s_cardValue;
   wire [4:0] s_score;
   wire [4:0] \core/I_1/regAdd ;
   wire [4:0] \core/I_1/regLoad ;
   wire [3:0] \core/I_2/state ;

   CLKBUFX2 FE_PHC524_core_I_1_regLoad_2_ (.Y(FE_PHN524_core_I_1_regLoad_2_),
	.A(FE_PHN337_core_I_1_regLoad_2_));
   DLY3X4 FE_PHC523_FE_OFN1_s_start (.Y(FE_PHN523_FE_OFN1_s_start),
	.A(FE_PHN455_FE_OFN1_s_start));
   CLKBUFX2 FE_PHC522_s_score_4_ (.Y(FE_PHN522_s_score_4_),
	.A(FE_PHN463_s_score_4_));
   CLKBUFX2 FE_PHC521_FE_OFN0_s_cardReady (.Y(FE_PHN521_FE_OFN0_s_cardReady),
	.A(FE_PHN506_FE_OFN0_s_cardReady));
   CLKBUFX2 FE_PHC520_n56 (.Y(FE_PHN520_n56),
	.A(FE_PHN507_n56));
   CLKBUFX2 FE_PHC519_n62 (.Y(FE_PHN519_n62),
	.A(FE_PHN503_n62));
   DLY1X1 FE_PHC518_n93 (.Y(FE_PHN518_n93),
	.A(FE_PHN511_n93));
   DLY4X4 FE_PHC517_n60 (.Y(FE_PHN517_n60),
	.A(FE_PHN297_n60));
   DLY4X4 FE_PHC516_FE_OFN1_s_start (.Y(FE_PHN516_FE_OFN1_s_start),
	.A(FE_PHN357_FE_OFN1_s_start));
   CLKBUFX2 FE_PHC515_core_I_2_cardReadySync (.Y(FE_PHN515_core_I_2_cardReadySync),
	.A(FE_PHN468_core_I_2_cardReadySync));
   DLY4X4 FE_PHC514_n60 (.Y(FE_PHN514_n60),
	.A(FE_PHN517_n60));
   DLY3X4 FE_PHC513_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN513_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN491_FE_OFN5_s_cardValue_0_));
   DLY3X4 FE_PHC512_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN512_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN490_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC511_n93 (.Y(FE_PHN501_n93),
	.A(FE_PHN518_n93));
   DLY4X4 FE_PHC510_s_score_1_ (.Y(FE_PHN510_s_score_1_),
	.A(FE_PHN492_s_score_1_));
   DLY4X4 FE_PHC509_s_score_3_ (.Y(FE_PHN509_s_score_3_),
	.A(FE_PHN488_s_score_3_));
   DLY4X4 FE_PHC508_s_score_2_ (.Y(FE_PHN508_s_score_2_),
	.A(FE_PHN473_s_score_2_));
   DLY4X4 FE_PHC507_n56 (.Y(FE_PHN507_n56),
	.A(FE_PHN429_n56));
   DLY4X4 FE_PHC506_FE_OFN0_s_cardReady (.Y(FE_PHN506_FE_OFN0_s_cardReady),
	.A(FE_PHN498_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC505_s_score_4_ (.Y(FE_PHN505_s_score_4_),
	.A(FE_PHN496_s_score_4_));
   DLY4X4 FE_PHC504_s_score_0_ (.Y(FE_PHN504_s_score_0_),
	.A(FE_PHN497_s_score_0_));
   DLY4X4 FE_PHC503_n62 (.Y(FE_PHN503_n62),
	.A(FE_PHN494_n62));
   DLY4X4 FE_PHC502_FE_OFN1_s_start (.Y(FE_PHN502_FE_OFN1_s_start),
	.A(FE_PHN471_FE_OFN1_s_start));
   DLY4X1 FE_PHC501_n93 (.Y(FE_PHN511_n93),
	.A(n93));
   DLY4X4 FE_PHC500_core_I_1_regLoad_3_ (.Y(FE_PHN500_core_I_1_regLoad_3_),
	.A(FE_PHN435_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC499_n60 (.Y(FE_PHN499_n60),
	.A(FE_PHN243_n60));
   DLY4X4 FE_PHC498_FE_OFN0_s_cardReady (.Y(FE_PHN498_FE_OFN0_s_cardReady),
	.A(FE_PHN410_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC497_s_score_0_ (.Y(FE_PHN497_s_score_0_),
	.A(FE_PHN474_s_score_0_));
   DLY4X4 FE_PHC496_s_score_4_ (.Y(FE_PHN496_s_score_4_),
	.A(FE_PHN483_s_score_4_));
   DLY4X4 FE_PHC495_n56 (.Y(FE_PHN495_n56),
	.A(FE_PHN520_n56));
   DLY4X4 FE_PHC494_n62 (.Y(FE_PHN494_n62),
	.A(FE_PHN481_n62));
   DLY4X4 FE_PHC493_FE_OFN1_s_start (.Y(FE_PHN493_FE_OFN1_s_start),
	.A(FE_PHN383_FE_OFN1_s_start));
   DLY4X4 FE_PHC492_s_score_1_ (.Y(FE_PHN492_s_score_1_),
	.A(FE_PHN456_s_score_1_));
   DLY4X4 FE_PHC491_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN491_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN443_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC490_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN490_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN442_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC489_n59 (.Y(FE_PHN489_n59),
	.A(FE_PHN271_n59));
   DLY4X4 FE_PHC488_s_score_3_ (.Y(FE_PHN488_s_score_3_),
	.A(FE_PHN476_s_score_3_));
   DLY4X4 FE_PHC487_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN487_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN477_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC486_s_score_2_ (.Y(FE_PHN486_s_score_2_),
	.A(FE_PHN439_s_score_2_));
   DLY4X4 FE_PHC485_core_I_2_cardReadySync (.Y(FE_PHN485_core_I_2_cardReadySync),
	.A(FE_PHN417_core_I_2_cardReadySync));
   DLY4X4 FE_PHC484_core_I_1_regLoad_2_ (.Y(FE_PHN484_core_I_1_regLoad_2_),
	.A(FE_PHN438_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC483_s_score_4_ (.Y(FE_PHN483_s_score_4_),
	.A(FE_PHN433_s_score_4_));
   DLY4X4 FE_PHC482_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN482_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN466_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC481_n62 (.Y(FE_PHN481_n62),
	.A(FE_PHN464_n62));
   DLY4X4 FE_PHC480_FE_OFN0_s_cardReady (.Y(FE_PHN480_FE_OFN0_s_cardReady),
	.A(FE_PHN432_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC479_n56 (.Y(FE_PHN479_n56),
	.A(FE_PHN413_n56));
   DLY4X4 FE_PHC478_s_score_1_ (.Y(FE_PHN478_s_score_1_),
	.A(FE_PHN510_s_score_1_));
   DLY4X4 FE_PHC477_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN477_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN444_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC476_s_score_3_ (.Y(FE_PHN476_s_score_3_),
	.A(FE_PHN441_s_score_3_));
   DLY4X4 FE_PHC475_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN475_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN459_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC474_s_score_0_ (.Y(FE_PHN474_s_score_0_),
	.A(FE_PHN465_s_score_0_));
   DLY4X4 FE_PHC473_s_score_2_ (.Y(FE_PHN473_s_score_2_),
	.A(FE_PHN467_s_score_2_));
   DLY4X4 FE_PHC472_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN472_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN458_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC471_FE_OFN1_s_start (.Y(FE_PHN471_FE_OFN1_s_start),
	.A(FE_PHN523_FE_OFN1_s_start));
   DLY4X4 FE_PHC470_core_I_1_regLoad_4_ (.Y(FE_PHN470_core_I_1_regLoad_4_),
	.A(FE_PHN436_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC469_core_I_1_regLoad_3_ (.Y(FE_PHN469_core_I_1_regLoad_3_),
	.A(FE_PHN500_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC468_core_I_2_cardReadySync (.Y(FE_PHN468_core_I_2_cardReadySync),
	.A(FE_PHN451_core_I_2_cardReadySync));
   DLY4X4 FE_PHC467_s_score_2_ (.Y(FE_PHN467_s_score_2_),
	.A(FE_PHN416_s_score_2_));
   DLY4X4 FE_PHC466_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN466_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN448_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC465_s_score_0_ (.Y(FE_PHN465_s_score_0_),
	.A(FE_PHN390_s_score_0_));
   DLY4X4 FE_PHC464_n62 (.Y(FE_PHN464_n62),
	.A(FE_PHN447_n62));
   DLY4X4 FE_PHC463_s_score_4_ (.Y(FE_PHN463_s_score_4_),
	.A(FE_PHN449_s_score_4_));
   DLY4X4 FE_PHC462_FE_OFN0_s_cardReady (.Y(FE_PHN462_FE_OFN0_s_cardReady),
	.A(FE_PHN396_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC461_n56 (.Y(FE_PHN461_n56),
	.A(FE_PHN445_n56));
   DLY4X4 FE_PHC460_n59 (.Y(FE_PHN460_n59),
	.A(FE_PHN304_n59));
   DLY4X4 FE_PHC459_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN459_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN513_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC458_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN458_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN512_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC457_s_score_3_ (.Y(FE_PHN457_s_score_3_),
	.A(FE_PHN509_s_score_3_));
   DLY4X4 FE_PHC456_s_score_1_ (.Y(FE_PHN456_s_score_1_),
	.A(FE_PHN440_s_score_1_));
   DLY4X4 FE_PHC455_FE_OFN1_s_start (.Y(FE_PHN455_FE_OFN1_s_start),
	.A(FE_PHN334_FE_OFN1_s_start));
   DLY4X4 FE_PHC454_core_I_1_regLoad_4_ (.Y(FE_PHN454_core_I_1_regLoad_4_),
	.A(FE_PHN470_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC453_core_I_1_regLoad_3_ (.Y(FE_PHN453_core_I_1_regLoad_3_),
	.A(FE_PHN418_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC452_core_I_1_regLoad_2_ (.Y(FE_PHN452_core_I_1_regLoad_2_),
	.A(FE_PHN421_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC451_core_I_2_cardReadySync (.Y(FE_PHN451_core_I_2_cardReadySync),
	.A(FE_PHN385_core_I_2_cardReadySync));
   DLY4X4 FE_PHC450_s_score_0_ (.Y(FE_PHN450_s_score_0_),
	.A(FE_PHN504_s_score_0_));
   DLY4X4 FE_PHC449_s_score_4_ (.Y(FE_PHN449_s_score_4_),
	.A(FE_PHN505_s_score_4_));
   DLY4X4 FE_PHC448_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN448_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN397_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC447_n62 (.Y(FE_PHN447_n62),
	.A(FE_PHN431_n62));
   DLY4X4 FE_PHC446_FE_OFN0_s_cardReady (.Y(FE_PHN446_FE_OFN0_s_cardReady),
	.A(FE_PHN324_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC445_n56 (.Y(FE_PHN445_n56),
	.A(FE_PHN495_n56));
   DLY4X4 FE_PHC444_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN444_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN392_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC443_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN443_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN391_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC442_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN442_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN393_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC441_s_score_3_ (.Y(FE_PHN441_s_score_3_),
	.A(FE_PHN424_s_score_3_));
   DLY4X4 FE_PHC440_s_score_1_ (.Y(FE_PHN440_s_score_1_),
	.A(FE_PHN428_s_score_1_));
   DLY4X4 FE_PHC439_s_score_2_ (.Y(FE_PHN439_s_score_2_),
	.A(FE_PHN423_s_score_2_));
   DLY4X4 FE_PHC438_core_I_1_regLoad_2_ (.Y(FE_PHN438_core_I_1_regLoad_2_),
	.A(FE_PHN452_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC437_FE_OFN1_s_start (.Y(FE_PHN437_FE_OFN1_s_start),
	.A(FE_PHN286_FE_OFN1_s_start));
   DLY4X4 FE_PHC436_core_I_1_regLoad_4_ (.Y(FE_PHN436_core_I_1_regLoad_4_),
	.A(FE_PHN419_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC435_core_I_1_regLoad_3_ (.Y(FE_PHN435_core_I_1_regLoad_3_),
	.A(FE_PHN402_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC434_core_I_2_cardReadySync (.Y(FE_PHN434_core_I_2_cardReadySync),
	.A(FE_PHN485_core_I_2_cardReadySync));
   DLY4X4 FE_PHC433_s_score_4_ (.Y(FE_PHN433_s_score_4_),
	.A(s_score[4]));
   DLY4X4 FE_PHC432_FE_OFN0_s_cardReady (.Y(FE_PHN432_FE_OFN0_s_cardReady),
	.A(FE_PHN521_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC431_n62 (.Y(FE_PHN431_n62),
	.A(FE_PHN409_n62));
   DLY4X4 FE_PHC430_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN430_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN412_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC429_n56 (.Y(FE_PHN429_n56),
	.A(FE_PHN479_n56));
   DLY4X4 FE_PHC428_s_score_1_ (.Y(FE_PHN428_s_score_1_),
	.A(FE_PHN389_s_score_1_));
   DLY4X4 FE_PHC427_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN427_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN408_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC426_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN426_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN406_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC425_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN425_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN407_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC424_s_score_3_ (.Y(FE_PHN424_s_score_3_),
	.A(FE_PHN415_s_score_3_));
   DLY4X4 FE_PHC423_s_score_2_ (.Y(FE_PHN423_s_score_2_),
	.A(FE_PHN508_s_score_2_));
   DLY4X4 FE_PHC422_s_score_0_ (.Y(FE_PHN422_s_score_0_),
	.A(FE_PHN411_s_score_0_));
   DLY4X4 FE_PHC421_core_I_1_regLoad_2_ (.Y(FE_PHN421_core_I_1_regLoad_2_),
	.A(FE_PHN401_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC420_FE_OFN1_s_start (.Y(FE_PHN420_FE_OFN1_s_start),
	.A(FE_PHN403_FE_OFN1_s_start));
   DLY4X4 FE_PHC419_core_I_1_regLoad_4_ (.Y(FE_PHN419_core_I_1_regLoad_4_),
	.A(FE_PHN366_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC418_core_I_1_regLoad_3_ (.Y(FE_PHN418_core_I_1_regLoad_3_),
	.A(FE_PHN469_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC417_core_I_2_cardReadySync (.Y(FE_PHN417_core_I_2_cardReadySync),
	.A(FE_PHN400_core_I_2_cardReadySync));
   DLY4X4 FE_PHC416_s_score_2_ (.Y(FE_PHN416_s_score_2_),
	.A(s_score[2]));
   DLY4X4 FE_PHC415_s_score_3_ (.Y(FE_PHN415_s_score_3_),
	.A(s_score[3]));
   DLY4X1 FE_PHC414_s_score_4_ (.Y(FE_PHN414_s_score_4_),
	.A(FE_PHN522_s_score_4_));
   DLY4X4 FE_PHC413_n56 (.Y(FE_PHN413_n56),
	.A(FE_PHN394_n56));
   DLY4X4 FE_PHC412_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN412_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN482_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC411_s_score_0_ (.Y(FE_PHN411_s_score_0_),
	.A(FE_PHN450_s_score_0_));
   DLY4X4 FE_PHC410_FE_OFN0_s_cardReady (.Y(FE_PHN410_FE_OFN0_s_cardReady),
	.A(FE_PHN344_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC409_n62 (.Y(FE_PHN409_n62),
	.A(FE_PHN395_n62));
   DLY4X4 FE_PHC408_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN408_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN487_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC407_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN407_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN475_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC406_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN406_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN472_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC405_s_score_1_ (.Y(FE_PHN405_s_score_1_),
	.A(FE_PHN478_s_score_1_));
   DLY4X4 FE_PHC404_core_I_1_regLoad_4_ (.Y(FE_PHN404_core_I_1_regLoad_4_),
	.A(FE_PHN454_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC403_FE_OFN1_s_start (.Y(FE_PHN403_FE_OFN1_s_start),
	.A(FE_PHN172_FE_OFN1_s_start));
   DLY4X4 FE_PHC402_core_I_1_regLoad_3_ (.Y(FE_PHN402_core_I_1_regLoad_3_),
	.A(FE_PHN382_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC401_core_I_1_regLoad_2_ (.Y(FE_PHN401_core_I_1_regLoad_2_),
	.A(FE_PHN360_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC400_core_I_2_cardReadySync (.Y(FE_PHN400_core_I_2_cardReadySync),
	.A(FE_PHN515_core_I_2_cardReadySync));
   DLY4X1 FE_PHC399_s_score_2_ (.Y(FE_PHN399_s_score_2_),
	.A(FE_PHN486_s_score_2_));
   DLY4X1 FE_PHC398_s_score_3_ (.Y(FE_PHN398_s_score_3_),
	.A(FE_PHN457_s_score_3_));
   DLY4X4 FE_PHC397_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN397_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN380_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC396_FE_OFN0_s_cardReady (.Y(FE_PHN396_FE_OFN0_s_cardReady),
	.A(FE_PHN374_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC395_n62 (.Y(FE_PHN395_n62),
	.A(FE_PHN350_n62));
   DLY4X1 FE_PHC394_n56 (.Y(FE_PHN369_n56),
	.A(FE_PHN461_n56));
   DLY4X4 FE_PHC393_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN393_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN378_FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC392_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN392_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN379_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC391_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN391_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN377_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC390_s_score_0_ (.Y(FE_PHN390_s_score_0_),
	.A(FE_PHN376_s_score_0_));
   DLY4X4 FE_PHC389_s_score_1_ (.Y(FE_PHN389_s_score_1_),
	.A(FE_PHN348_s_score_1_));
   DLY4X4 FE_PHC388_n49 (.Y(FE_PHN388_n49),
	.A(FE_PHN372_n49));
   DLY4X4 FE_PHC387_n53 (.Y(FE_PHN387_n53),
	.A(FE_PHN365_n53));
   DLY4X1 FE_PHC386_n88 (.Y(FE_PHN386_n88),
	.A(FE_PHN375_n88));
   DLY4X4 FE_PHC385_core_I_2_cardReadySync (.Y(FE_PHN385_core_I_2_cardReadySync),
	.A(\core/I_2/cardReadySync ));
   DLY4X1 FE_PHC384_core_I_1_regLoad_4_ (.Y(FE_PHN384_core_I_1_regLoad_4_),
	.A(FE_PHN404_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC383_FE_OFN1_s_start (.Y(FE_PHN383_FE_OFN1_s_start),
	.A(FE_PHN516_FE_OFN1_s_start));
   DLY4X4 FE_PHC382_core_I_1_regLoad_3_ (.Y(FE_PHN358_core_I_1_regLoad_3_),
	.A(FE_PHN453_core_I_1_regLoad_3_));
   DLY4X4 FE_PHC381_core_I_1_regLoad_2_ (.Y(FE_PHN381_core_I_1_regLoad_2_),
	.A(FE_PHN484_core_I_1_regLoad_2_));
   DLY4X4 FE_PHC380_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN380_FE_OFN3_s_cardValue_2_),
	.A(FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC379_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN379_FE_OFN2_s_cardValue_3_),
	.A(FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC378_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN378_FE_OFN4_s_cardValue_1_),
	.A(FE_OFN4_s_cardValue_1_));
   DLY4X4 FE_PHC377_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN377_FE_OFN5_s_cardValue_0_),
	.A(FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC376_s_score_0_ (.Y(FE_PHN376_s_score_0_),
	.A(s_score[0]));
   DLY4X1 FE_PHC375_n88 (.Y(FE_PHN375_n88),
	.A(FE_PHN356_n88));
   DLY4X4 FE_PHC374_FE_OFN0_s_cardReady (.Y(FE_PHN374_FE_OFN0_s_cardReady),
	.A(FE_PHN480_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC373_n51 (.Y(FE_PHN373_n51),
	.A(FE_PHN347_n51));
   DLY4X4 FE_PHC372_n49 (.Y(FE_PHN372_n49),
	.A(FE_PHN346_n49));
   DLY4X4 FE_PHC371_n50 (.Y(FE_PHN371_n50),
	.A(FE_PHN345_n50));
   DLY4X4 FE_PHC370_n64 (.Y(FE_PHN370_n64),
	.A(FE_PHN342_n64));
   DLY4X4 FE_PHC369_n56 (.Y(FE_PHN394_n56),
	.A(FE_PHN351_n56));
   DLY4X1 FE_PHC368_n62 (.Y(FE_PHN368_n62),
	.A(FE_PHN519_n62));
   DLY4X1 FE_PHC367_core_I_2_cardReadySync (.Y(FE_PHN367_core_I_2_cardReadySync),
	.A(FE_PHN434_core_I_2_cardReadySync));
   DLY4X1 FE_PHC366_core_I_1_regLoad_4_ (.Y(FE_PHN366_core_I_1_regLoad_4_),
	.A(\core/I_1/regLoad [4]));
   DLY4X4 FE_PHC365_n53 (.Y(FE_PHN365_n53),
	.A(FE_PHN300_n53));
   DLY4X4 FE_PHC364_n54 (.Y(FE_PHN364_n54),
	.A(FE_PHN343_n54));
   DLY4X4 FE_PHC363_s_score_1_ (.Y(FE_PHN363_s_score_1_),
	.A(FE_PHN405_s_score_1_));
   DLY4X4 FE_PHC362_n65 (.Y(FE_PHN362_n65),
	.A(FE_PHN339_n65));
   DLY4X4 FE_PHC361_n66 (.Y(FE_PHN361_n66),
	.A(FE_PHN340_n66));
   DLY4X4 FE_PHC360_core_I_1_regLoad_2_ (.Y(FE_PHN360_core_I_1_regLoad_2_),
	.A(\core/I_1/regLoad [2]));
   DLY4X4 FE_PHC359_n55 (.Y(FE_PHN359_n55),
	.A(FE_PHN341_n55));
   DLY4X4 FE_PHC358_core_I_1_regLoad_3_ (.Y(FE_PHN382_core_I_1_regLoad_3_),
	.A(\core/I_1/regLoad [3]));
   DLY4X4 FE_PHC357_FE_OFN1_s_start (.Y(FE_PHN357_FE_OFN1_s_start),
	.A(FE_PHN502_FE_OFN1_s_start));
   DLY2X1 FE_PHC356_n88 (.Y(FE_PHN356_n88),
	.A(n88));
   DLY4X1 FE_PHC355_FE_OFN3_s_cardValue_2_ (.Y(FE_PHN355_FE_OFN3_s_cardValue_2_),
	.A(FE_PHN430_FE_OFN3_s_cardValue_2_));
   DLY4X4 FE_PHC354_FE_OFN5_s_cardValue_0_ (.Y(FE_PHN354_FE_OFN5_s_cardValue_0_),
	.A(FE_PHN425_FE_OFN5_s_cardValue_0_));
   DLY4X4 FE_PHC353_FE_OFN4_s_cardValue_1_ (.Y(FE_PHN353_FE_OFN4_s_cardValue_1_),
	.A(FE_PHN426_FE_OFN4_s_cardValue_1_));
   DLY4X1 FE_PHC352_FE_OFN2_s_cardValue_3_ (.Y(FE_PHN352_FE_OFN2_s_cardValue_3_),
	.A(FE_PHN427_FE_OFN2_s_cardValue_3_));
   DLY4X4 FE_PHC351_n56 (.Y(FE_PHN351_n56),
	.A(n56));
   DLY4X4 FE_PHC350_n62 (.Y(FE_PHN350_n62),
	.A(n62));
   DLY4X1 FE_PHC349_s_score_0_ (.Y(FE_PHN349_s_score_0_),
	.A(FE_PHN422_s_score_0_));
   DLY4X4 FE_PHC348_s_score_1_ (.Y(FE_PHN348_s_score_1_),
	.A(s_score[1]));
   DLY4X4 FE_PHC347_n51 (.Y(FE_PHN347_n51),
	.A(FE_PHN219_n51));
   DLY4X4 FE_PHC346_n49 (.Y(FE_PHN346_n49),
	.A(FE_PHN326_n49));
   DLY4X4 FE_PHC345_n50 (.Y(FE_PHN345_n50),
	.A(FE_PHN329_n50));
   DLY4X4 FE_PHC344_FE_OFN0_s_cardReady (.Y(FE_PHN344_FE_OFN0_s_cardReady),
	.A(FE_PHN277_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC343_n54 (.Y(FE_PHN343_n54),
	.A(FE_PHN330_n54));
   DLY4X4 FE_PHC342_n64 (.Y(FE_PHN342_n64),
	.A(FE_PHN242_n64));
   DLY4X4 FE_PHC341_n55 (.Y(FE_PHN341_n55),
	.A(FE_PHN320_n55));
   DLY4X4 FE_PHC340_n66 (.Y(FE_PHN340_n66),
	.A(FE_PHN319_n66));
   DLY4X4 FE_PHC339_n65 (.Y(FE_PHN339_n65),
	.A(FE_PHN325_n65));
   DLY4X4 FE_PHC338_n53 (.Y(FE_PHN338_n53),
	.A(FE_PHN328_n53));
   DLY4X1 FE_PHC337_core_I_1_regLoad_2_ (.Y(FE_PHN337_core_I_1_regLoad_2_),
	.A(FE_PHN381_core_I_1_regLoad_2_));
   DLY4X1 FE_PHC336_core_I_1_regLoad_3_ (.Y(FE_PHN336_core_I_1_regLoad_3_),
	.A(FE_PHN358_core_I_1_regLoad_3_));
   DLY4X1 FE_PHC335_core_I_1_regLoad_4_ (.Y(FE_PHN335_core_I_1_regLoad_4_),
	.A(FE_PHN384_core_I_1_regLoad_4_));
   DLY4X4 FE_PHC334_FE_OFN1_s_start (.Y(FE_PHN334_FE_OFN1_s_start),
	.A(FE_PHN202_FE_OFN1_s_start));
   DLY4X4 FE_PHC333_core_I_1_regAdd_4_ (.Y(FE_PHN333_core_I_1_regAdd_4_),
	.A(FE_PHN73_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC332_core_I_1_regAdd_3_ (.Y(FE_PHN332_core_I_1_regAdd_3_),
	.A(FE_PHN101_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC331_n48 (.Y(FE_PHN331_n48),
	.A(FE_PHN249_n48));
   DLY4X4 FE_PHC330_n54 (.Y(FE_PHN330_n54),
	.A(FE_PHN216_n54));
   DLY4X4 FE_PHC329_n50 (.Y(FE_PHN329_n50),
	.A(FE_PHN264_n50));
   DLY4X4 FE_PHC328_n53 (.Y(FE_PHN328_n53),
	.A(FE_PHN387_n53));
   DLY4X4 FE_PHC327_n59 (.Y(FE_PHN327_n59),
	.A(FE_PHN460_n59));
   DLY4X4 FE_PHC326_n49 (.Y(FE_PHN326_n49),
	.A(FE_PHN302_n49));
   DLY4X4 FE_PHC325_n65 (.Y(FE_PHN325_n65),
	.A(FE_PHN299_n65));
   DLY4X4 FE_PHC324_FE_OFN0_s_cardReady (.Y(FE_PHN324_FE_OFN0_s_cardReady),
	.A(FE_PHN303_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC323_n58 (.Y(FE_PHN323_n58),
	.A(FE_PHN217_n58));
   DLY4X4 FE_PHC322_n60 (.Y(FE_PHN322_n60),
	.A(FE_PHN273_n60));
   DLY4X4 FE_PHC321_n64 (.Y(FE_PHN321_n64),
	.A(FE_PHN298_n64));
   DLY4X4 FE_PHC320_n55 (.Y(FE_PHN320_n55),
	.A(FE_PHN218_n55));
   DLY4X4 FE_PHC319_n66 (.Y(FE_PHN319_n66),
	.A(FE_PHN174_n66));
   DLY4X4 FE_PHC318_n57 (.Y(FE_PHN288_n57),
	.A(FE_PHN318_n57));
   DLY4X4 FE_PHC317_n61 (.Y(FE_PHN317_n61),
	.A(FE_PHN292_n61));
   DLY4X4 FE_PHC316_n63 (.Y(FE_PHN316_n63),
	.A(FE_PHN293_n63));
   DLY4X4 FE_PHC315_n52 (.Y(FE_PHN315_n52),
	.A(FE_PHN301_n52));
   DLY4X4 FE_PHC314_n51 (.Y(FE_PHN314_n51),
	.A(FE_PHN86_n51));
   DLY4X4 FE_PHC313_FE_OFN1_s_start (.Y(FE_PHN313_FE_OFN1_s_start),
	.A(FE_PHN112_FE_OFN1_s_start));
   DLY4X4 FE_PHC312_core_I_1_regAdd_1_ (.Y(FE_PHN312_core_I_1_regAdd_1_),
	.A(FE_PHN285_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC311_core_I_1_regAdd_0_ (.Y(FE_PHN311_core_I_1_regAdd_0_),
	.A(FE_PHN229_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC310_core_I_1_regLoad_0_ (.Y(FE_PHN257_core_I_1_regLoad_0_),
	.A(FE_PHN310_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC309_core_I_1_regLoad_1_ (.Y(FE_PHN309_core_I_1_regLoad_1_),
	.A(FE_PHN281_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC308_core_I_2_state_3_ (.Y(FE_PHN280_core_I_2_state_3_),
	.A(FE_PHN308_core_I_2_state_3_));
   DLY4X4 FE_PHC307_core_I_2_state_1_ (.Y(FE_PHN307_core_I_2_state_1_),
	.A(FE_PHN195_core_I_2_state_1_));
   DLY4X4 FE_PHC306_core_I_2_state_0_ (.Y(FE_PHN306_core_I_2_state_0_),
	.A(FE_PHN252_core_I_2_state_0_));
   DLY4X4 FE_PHC305_core_I_2_state_2_ (.Y(FE_PHN305_core_I_2_state_2_),
	.A(FE_PHN226_core_I_2_state_2_));
   DLY4X4 FE_PHC304_n59 (.Y(FE_PHN304_n59),
	.A(FE_PHN489_n59));
   DLY4X4 FE_PHC303_FE_OFN0_s_cardReady (.Y(FE_PHN303_FE_OFN0_s_cardReady),
	.A(FE_PHN462_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC302_n49 (.Y(FE_PHN302_n49),
	.A(FE_PHN189_n49));
   DLY4X4 FE_PHC301_n52 (.Y(FE_PHN301_n52),
	.A(FE_PHN87_n52));
   DLY4X4 FE_PHC300_n53 (.Y(FE_PHN300_n53),
	.A(FE_PHN245_n53));
   DLY4X4 FE_PHC299_n65 (.Y(FE_PHN299_n65),
	.A(FE_PHN214_n65));
   DLY4X4 FE_PHC298_n64 (.Y(FE_PHN298_n64),
	.A(FE_PHN190_n64));
   DLY4X4 FE_PHC297_n60 (.Y(FE_PHN297_n60),
	.A(FE_PHN220_n60));
   DLY4X4 FE_PHC296_n50 (.Y(FE_PHN296_n50),
	.A(FE_PHN371_n50));
   DLY4X4 FE_PHC295_n58 (.Y(FE_PHN295_n58),
	.A(FE_PHN274_n58));
   DLY4X4 FE_PHC294_n66 (.Y(FE_PHN294_n66),
	.A(FE_PHN361_n66));
   DLY4X4 FE_PHC293_n63 (.Y(FE_PHN293_n63),
	.A(FE_PHN211_n63));
   DLY4X4 FE_PHC292_n61 (.Y(FE_PHN292_n61),
	.A(FE_PHN267_n61));
   DLY4X4 FE_PHC291_n51 (.Y(FE_PHN291_n51),
	.A(FE_PHN186_n51));
   DLY4X4 FE_PHC290_n54 (.Y(FE_PHN290_n54),
	.A(FE_PHN263_n54));
   DLY4X4 FE_PHC289_n48 (.Y(FE_PHN289_n48),
	.A(FE_PHN265_n48));
   DLY4X4 FE_PHC288_n57 (.Y(FE_PHN318_n57),
	.A(FE_PHN173_n57));
   DLY4X4 FE_PHC287_n55 (.Y(FE_PHN287_n55),
	.A(FE_PHN180_n55));
   DLY4X4 FE_PHC286_FE_OFN1_s_start (.Y(FE_PHN286_FE_OFN1_s_start),
	.A(FE_PHN259_FE_OFN1_s_start));
   DLY4X4 FE_PHC285_core_I_1_regAdd_1_ (.Y(FE_PHN258_core_I_1_regAdd_1_),
	.A(FE_PHN312_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC284_core_I_1_regLoad_0_ (.Y(FE_PHN284_core_I_1_regLoad_0_),
	.A(FE_PHN257_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC283_core_I_1_regAdd_0_ (.Y(FE_PHN283_core_I_1_regAdd_0_),
	.A(FE_PHN256_core_I_1_regAdd_0_));
   DLY4X1 FE_PHC282_core_I_2_state_1_ (.Y(FE_PHN282_core_I_2_state_1_),
	.A(FE_PHN135_core_I_2_state_1_));
   DLY4X4 FE_PHC281_core_I_1_regLoad_1_ (.Y(FE_PHN255_core_I_1_regLoad_1_),
	.A(FE_PHN309_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC280_core_I_2_state_3_ (.Y(FE_PHN254_core_I_2_state_3_),
	.A(FE_PHN280_core_I_2_state_3_));
   DLY4X4 FE_PHC279_core_I_2_state_2_ (.Y(FE_PHN279_core_I_2_state_2_),
	.A(FE_PHN305_core_I_2_state_2_));
   DLY4X4 FE_PHC278_core_I_2_state_0_ (.Y(FE_PHN278_core_I_2_state_0_),
	.A(FE_PHN194_core_I_2_state_0_));
   DLY4X4 FE_PHC277_FE_OFN0_s_cardReady (.Y(FE_PHN277_FE_OFN0_s_cardReady),
	.A(FE_PHN215_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC276_n51 (.Y(FE_PHN276_n51),
	.A(FE_PHN244_n51));
   DLY4X4 FE_PHC275_n53 (.Y(FE_PHN275_n53),
	.A(FE_PHN338_n53));
   DLY4X4 FE_PHC274_n58 (.Y(FE_PHN274_n58),
	.A(FE_PHN323_n58));
   DLY4X4 FE_PHC273_n60 (.Y(FE_PHN273_n60),
	.A(FE_PHN514_n60));
   DLY4X4 FE_PHC272_n49 (.Y(FE_PHN272_n49),
	.A(FE_PHN388_n49));
   DLY4X4 FE_PHC271_n59 (.Y(FE_PHN271_n59),
	.A(FE_PHN232_n59));
   DLY4X4 FE_PHC270_n64 (.Y(FE_PHN270_n64),
	.A(FE_PHN370_n64));
   DLY4X4 FE_PHC269_n57 (.Y(FE_PHN269_n57),
	.A(FE_PHN288_n57));
   DLY4X4 FE_PHC268_n55 (.Y(FE_PHN268_n55),
	.A(FE_PHN239_n55));
   DLY4X4 FE_PHC267_n61 (.Y(FE_PHN240_n61),
	.A(FE_PHN317_n61));
   DLY4X4 FE_PHC266_n63 (.Y(FE_PHN266_n63),
	.A(FE_PHN238_n63));
   DLY4X4 FE_PHC265_n48 (.Y(FE_PHN265_n48),
	.A(FE_PHN331_n48));
   DLY4X4 FE_PHC264_n50 (.Y(FE_PHN264_n50),
	.A(FE_PHN178_n50));
   DLY4X4 FE_PHC263_n54 (.Y(FE_PHN263_n54),
	.A(FE_PHN248_n54));
   DLY4X4 FE_PHC262_n65 (.Y(FE_PHN262_n65),
	.A(FE_PHN246_n65));
   DLY4X4 FE_PHC261_n66 (.Y(FE_PHN261_n66),
	.A(FE_PHN212_n66));
   DLY4X4 FE_PHC260_n52 (.Y(FE_PHN260_n52),
	.A(FE_PHN315_n52));
   DLY4X4 FE_PHC259_FE_OFN1_s_start (.Y(FE_PHN259_FE_OFN1_s_start),
	.A(FE_PHN493_FE_OFN1_s_start));
   DLY4X4 FE_PHC258_core_I_1_regAdd_1_ (.Y(FE_PHN285_core_I_1_regAdd_1_),
	.A(FE_PHN230_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC257_core_I_1_regLoad_0_ (.Y(FE_PHN310_core_I_1_regLoad_0_),
	.A(FE_PHN228_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC256_core_I_1_regAdd_0_ (.Y(FE_PHN256_core_I_1_regAdd_0_),
	.A(FE_PHN311_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC255_core_I_1_regLoad_1_ (.Y(FE_PHN281_core_I_1_regLoad_1_),
	.A(FE_PHN167_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC254_core_I_2_state_3_ (.Y(FE_PHN227_core_I_2_state_3_),
	.A(FE_PHN254_core_I_2_state_3_));
   DLY4X4 FE_PHC253_core_I_2_state_2_ (.Y(FE_PHN253_core_I_2_state_2_),
	.A(FE_PHN279_core_I_2_state_2_));
   DLY4X4 FE_PHC252_core_I_2_state_0_ (.Y(FE_PHN252_core_I_2_state_0_),
	.A(FE_PHN225_core_I_2_state_0_));
   DLY4X4 FE_PHC251_core_I_2_state_1_ (.Y(FE_PHN251_core_I_2_state_1_),
	.A(FE_PHN106_core_I_2_state_1_));
   DLY4X4 FE_PHC250_core_I_1_regAdd_2_ (.Y(FE_PHN250_core_I_1_regAdd_2_),
	.A(FE_PHN222_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC249_n48 (.Y(FE_PHN249_n48),
	.A(FE_PHN159_n48));
   DLY4X4 FE_PHC248_n54 (.Y(FE_PHN248_n54),
	.A(FE_PHN364_n54));
   DLY4X4 FE_PHC247_FE_OFN0_s_cardReady (.Y(FE_PHN247_FE_OFN0_s_cardReady),
	.A(FE_PHN446_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC246_n65 (.Y(FE_PHN246_n65),
	.A(FE_PHN362_n65));
   DLY4X4 FE_PHC245_n53 (.Y(FE_PHN245_n53),
	.A(FE_PHN176_n53));
   DLY4X4 FE_PHC244_n51 (.Y(FE_PHN244_n51),
	.A(FE_PHN373_n51));
   DLY4X4 FE_PHC243_n60 (.Y(FE_PHN243_n60),
	.A(FE_PHN184_n60));
   DLY4X4 FE_PHC242_n64 (.Y(FE_PHN242_n64),
	.A(FE_PHN213_n64));
   DLY4X4 FE_PHC241_n58 (.Y(FE_PHN241_n58),
	.A(FE_PHN188_n58));
   DLY4X4 FE_PHC240_n61 (.Y(FE_PHN267_n61),
	.A(FE_PHN210_n61));
   DLY4X4 FE_PHC239_n55 (.Y(FE_PHN239_n55),
	.A(FE_PHN359_n55));
   DLY4X4 FE_PHC238_n63 (.Y(FE_PHN238_n63),
	.A(FE_PHN316_n63));
   DLY4X4 FE_PHC237_n52 (.Y(FE_PHN237_n52),
	.A(FE_PHN128_n52));
   DLY4X4 FE_PHC236_n49 (.Y(FE_PHN236_n49),
	.A(FE_PHN116_n49));
   DLY4X4 FE_PHC235_n66 (.Y(FE_PHN235_n66),
	.A(FE_PHN115_n66));
   DLY4X4 FE_PHC234_n50 (.Y(FE_PHN234_n50),
	.A(FE_PHN84_n50));
   DLY4X4 FE_PHC233_n57 (.Y(FE_PHN233_n57),
	.A(FE_PHN148_n57));
   DLY4X4 FE_PHC232_n59 (.Y(FE_PHN94_n59),
	.A(FE_PHN327_n59));
   DLY4X4 FE_PHC231_FE_OFN1_s_start (.Y(FE_PHN231_FE_OFN1_s_start),
	.A(FE_PHN142_FE_OFN1_s_start));
   DLY4X4 FE_PHC230_core_I_1_regAdd_1_ (.Y(FE_PHN201_core_I_1_regAdd_1_),
	.A(FE_PHN258_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC229_core_I_1_regAdd_0_ (.Y(FE_PHN229_core_I_1_regAdd_0_),
	.A(FE_PHN140_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC228_core_I_1_regLoad_0_ (.Y(FE_PHN228_core_I_1_regLoad_0_),
	.A(FE_PHN200_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC227_core_I_2_state_3_ (.Y(FE_PHN308_core_I_2_state_3_),
	.A(FE_PHN196_core_I_2_state_3_));
   DLY4X4 FE_PHC226_core_I_2_state_2_ (.Y(FE_PHN168_core_I_2_state_2_),
	.A(FE_PHN253_core_I_2_state_2_));
   DLY4X4 FE_PHC225_core_I_2_state_0_ (.Y(FE_PHN225_core_I_2_state_0_),
	.A(FE_PHN137_core_I_2_state_0_));
   DLY4X4 FE_PHC224_core_I_2_state_1_ (.Y(FE_PHN224_core_I_2_state_1_),
	.A(FE_PHN76_core_I_2_state_1_));
   DLY4X4 FE_PHC223_core_I_1_regLoad_1_ (.Y(FE_PHN223_core_I_1_regLoad_1_),
	.A(FE_PHN198_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC222_core_I_1_regAdd_2_ (.Y(FE_PHN222_core_I_1_regAdd_2_),
	.A(FE_PHN131_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC221_core_I_1_regAdd_3_ (.Y(FE_PHN221_core_I_1_regAdd_3_),
	.A(FE_PHN132_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC220_n60 (.Y(FE_PHN220_n60),
	.A(FE_PHN499_n60));
   DLY4X4 FE_PHC219_n51 (.Y(FE_PHN219_n51),
	.A(FE_PHN127_n51));
   DLY4X4 FE_PHC218_n55 (.Y(FE_PHN218_n55),
	.A(FE_PHN120_n55));
   DLY4X4 FE_PHC217_n58 (.Y(FE_PHN217_n58),
	.A(FE_PHN241_n58));
   DLY4X4 FE_PHC216_n54 (.Y(FE_PHN216_n54),
	.A(FE_PHN117_n54));
   DLY4X4 FE_PHC215_FE_OFN0_s_cardReady (.Y(FE_PHN215_FE_OFN0_s_cardReady),
	.A(FE_PHN121_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC214_n65 (.Y(FE_PHN214_n65),
	.A(FE_PHN126_n65));
   DLY4X4 FE_PHC213_n64 (.Y(FE_PHN213_n64),
	.A(FE_PHN321_n64));
   DLY4X4 FE_PHC212_n66 (.Y(FE_PHN212_n66),
	.A(FE_PHN235_n66));
   DLY4X4 FE_PHC211_n63 (.Y(FE_PHN211_n63),
	.A(FE_PHN144_n63));
   DLY4X4 FE_PHC210_n61 (.Y(FE_PHN177_n61),
	.A(FE_PHN240_n61));
   DLY4X4 FE_PHC209_n57 (.Y(FE_PHN209_n57),
	.A(FE_PHN233_n57));
   DLY4X4 FE_PHC208_n48 (.Y(FE_PHN208_n48),
	.A(FE_PHN182_n48));
   DLY4X4 FE_PHC207_n50 (.Y(FE_PHN207_n50),
	.A(FE_PHN156_n50));
   DLY4X4 FE_PHC206_n52 (.Y(FE_PHN206_n52),
	.A(FE_PHN58_n52));
   DLY4X4 FE_PHC205_n49 (.Y(FE_PHN205_n49),
	.A(FE_PHN30_n49));
   DLY4X4 FE_PHC204_n59 (.Y(FE_PHN123_n59),
	.A(FE_PHN204_n59));
   DLY4X4 FE_PHC203_n53 (.Y(FE_PHN203_n53),
	.A(FE_PHN82_n53));
   DLY4X4 FE_PHC202_FE_OFN1_s_start (.Y(FE_PHN202_FE_OFN1_s_start),
	.A(FE_PHN420_FE_OFN1_s_start));
   DLY4X4 FE_PHC201_core_I_1_regAdd_1_ (.Y(FE_PHN230_core_I_1_regAdd_1_),
	.A(FE_PHN171_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC200_core_I_1_regLoad_0_ (.Y(FE_PHN169_core_I_1_regLoad_0_),
	.A(FE_PHN284_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC199_core_I_1_regAdd_0_ (.Y(FE_PHN199_core_I_1_regAdd_0_),
	.A(FE_PHN170_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC198_core_I_1_regLoad_1_ (.Y(FE_PHN198_core_I_1_regLoad_1_),
	.A(FE_PHN255_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC197_core_I_2_state_2_ (.Y(FE_PHN226_core_I_2_state_2_),
	.A(FE_PHN197_core_I_2_state_2_));
   DLY4X4 FE_PHC196_core_I_2_state_3_ (.Y(FE_PHN196_core_I_2_state_3_),
	.A(FE_PHN107_core_I_2_state_3_));
   DLY4X4 FE_PHC195_core_I_2_state_1_ (.Y(FE_PHN195_core_I_2_state_1_),
	.A(FE_PHN166_core_I_2_state_1_));
   DLY4X4 FE_PHC194_core_I_2_state_0_ (.Y(FE_PHN194_core_I_2_state_0_),
	.A(FE_PHN164_core_I_2_state_0_));
   DLY4X4 FE_PHC193_core_I_1_regAdd_4_ (.Y(FE_PHN193_core_I_1_regAdd_4_),
	.A(FE_PHN103_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC192_core_I_1_regAdd_3_ (.Y(FE_PHN192_core_I_1_regAdd_3_),
	.A(FE_PHN162_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC191_core_I_1_regAdd_2_ (.Y(FE_PHN191_core_I_1_regAdd_2_),
	.A(FE_PHN161_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC190_n64 (.Y(FE_PHN190_n64),
	.A(FE_PHN113_n64));
   DLY4X4 FE_PHC189_n49 (.Y(FE_PHN189_n49),
	.A(FE_PHN158_n49));
   DLY4X4 FE_PHC188_n58 (.Y(FE_PHN188_n58),
	.A(FE_PHN151_n58));
   DLY4X4 FE_PHC187_n54 (.Y(FE_PHN187_n54),
	.A(FE_PHN290_n54));
   DLY4X4 FE_PHC186_n51 (.Y(FE_PHN186_n51),
	.A(FE_PHN155_n51));
   DLY4X4 FE_PHC185_FE_OFN0_s_cardReady (.Y(FE_PHN185_FE_OFN0_s_cardReady),
	.A(FE_PHN160_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC184_n60 (.Y(FE_PHN184_n60),
	.A(FE_PHN150_n60));
   DLY4X4 FE_PHC183_n59 (.Y(FE_PHN183_n59),
	.A(FE_PHN154_n59));
   DLY4X4 FE_PHC182_n48 (.Y(FE_PHN182_n48),
	.A(FE_PHN289_n48));
   DLY4X4 FE_PHC181_n63 (.Y(FE_PHN181_n63),
	.A(FE_PHN266_n63));
   DLY4X4 FE_PHC180_n55 (.Y(FE_PHN180_n55),
	.A(FE_PHN146_n55));
   DLY4X4 FE_PHC179_n65 (.Y(FE_PHN179_n65),
	.A(FE_PHN157_n65));
   DLY4X4 FE_PHC178_n50 (.Y(FE_PHN178_n50),
	.A(FE_PHN54_n50));
   DLY4X4 FE_PHC177_n61 (.Y(FE_PHN210_n61),
	.A(FE_PHN149_n61));
   DLY4X4 FE_PHC176_n53 (.Y(FE_PHN176_n53),
	.A(FE_PHN63_n53));
   DLY4X4 FE_PHC175_n52 (.Y(FE_PHN175_n52),
	.A(FE_PHN145_n52));
   DLY4X4 FE_PHC174_n66 (.Y(FE_PHN174_n66),
	.A(FE_PHN92_n66));
   DLY4X4 FE_PHC173_n57 (.Y(FE_PHN173_n57),
	.A(FE_PHN119_n57));
   DLY4X4 FE_PHC172_FE_OFN1_s_start (.Y(FE_PHN172_FE_OFN1_s_start),
	.A(FE_PHN99_FE_OFN1_s_start));
   DLY4X4 FE_PHC171_core_I_1_regAdd_1_ (.Y(FE_PHN171_core_I_1_regAdd_1_),
	.A(FE_PHN141_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC170_core_I_1_regAdd_0_ (.Y(FE_PHN170_core_I_1_regAdd_0_),
	.A(FE_PHN283_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC169_core_I_1_regLoad_0_ (.Y(FE_PHN138_core_I_1_regLoad_0_),
	.A(FE_PHN169_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC168_core_I_2_state_2_ (.Y(FE_PHN139_core_I_2_state_2_),
	.A(FE_PHN168_core_I_2_state_2_));
   DLY4X4 FE_PHC167_core_I_1_regLoad_1_ (.Y(FE_PHN134_core_I_1_regLoad_1_),
	.A(FE_PHN223_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC166_core_I_2_state_1_ (.Y(FE_PHN166_core_I_2_state_1_),
	.A(FE_PHN44_core_I_2_state_1_));
   DLY4X4 FE_PHC165_core_I_2_state_3_ (.Y(FE_PHN165_core_I_2_state_3_),
	.A(FE_PHN227_core_I_2_state_3_));
   DLY4X4 FE_PHC164_core_I_2_state_0_ (.Y(FE_PHN164_core_I_2_state_0_),
	.A(FE_PHN306_core_I_2_state_0_));
   DLY4X4 FE_PHC163_core_I_1_regAdd_4_ (.Y(FE_PHN163_core_I_1_regAdd_4_),
	.A(FE_PHN133_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC162_core_I_1_regAdd_3_ (.Y(FE_PHN162_core_I_1_regAdd_3_),
	.A(FE_PHN221_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC161_core_I_1_regAdd_2_ (.Y(FE_PHN161_core_I_1_regAdd_2_),
	.A(FE_PHN250_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC160_FE_OFN0_s_cardReady (.Y(FE_PHN160_FE_OFN0_s_cardReady),
	.A(FE_PHN247_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC159_n48 (.Y(FE_PHN159_n48),
	.A(FE_PHN85_n48));
   DLY4X4 FE_PHC158_n49 (.Y(FE_PHN158_n49),
	.A(FE_PHN62_n49));
   DLY4X4 FE_PHC157_n65 (.Y(FE_PHN157_n65),
	.A(FE_PHN262_n65));
   DLY4X4 FE_PHC156_n50 (.Y(FE_PHN156_n50),
	.A(FE_PHN129_n50));
   DLY4X4 FE_PHC155_n51 (.Y(FE_PHN155_n51),
	.A(FE_PHN276_n51));
   DLY4X4 FE_PHC154_n59 (.Y(FE_PHN204_n59),
	.A(FE_PHN183_n59));
   DLY4X4 FE_PHC153_n64 (.Y(FE_PHN153_n64),
	.A(FE_PHN270_n64));
   DLY4X4 FE_PHC152_n53 (.Y(FE_PHN152_n53),
	.A(FE_PHN125_n53));
   DLY4X4 FE_PHC151_n58 (.Y(FE_PHN124_n58),
	.A(FE_PHN295_n58));
   DLY4X4 FE_PHC150_n60 (.Y(FE_PHN150_n60),
	.A(FE_PHN98_n60));
   DLY4X4 FE_PHC149_n61 (.Y(FE_PHN149_n61),
	.A(FE_PHN26_n61));
   DLY4X4 FE_PHC148_n57 (.Y(FE_PHN148_n57),
	.A(FE_PHN269_n57));
   DLY4X4 FE_PHC147_n66 (.Y(FE_PHN147_n66),
	.A(FE_PHN294_n66));
   DLY4X4 FE_PHC146_n55 (.Y(FE_PHN146_n55),
	.A(FE_PHN268_n55));
   DLY4X4 FE_PHC145_n52 (.Y(FE_PHN145_n52),
	.A(FE_PHN237_n52));
   DLY4X4 FE_PHC144_n63 (.Y(FE_PHN144_n63),
	.A(FE_PHN114_n63));
   DLY4X4 FE_PHC143_n54 (.Y(FE_PHN143_n54),
	.A(FE_PHN55_n54));
   DLY4X4 FE_PHC142_FE_OFN1_s_start (.Y(FE_PHN142_FE_OFN1_s_start),
	.A(FE_PHN313_FE_OFN1_s_start));
   DLY4X4 FE_PHC141_core_I_1_regAdd_1_ (.Y(FE_PHN141_core_I_1_regAdd_1_),
	.A(FE_PHN81_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC140_core_I_1_regAdd_0_ (.Y(FE_PHN140_core_I_1_regAdd_0_),
	.A(FE_PHN79_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC139_core_I_2_state_2_ (.Y(FE_PHN110_core_I_2_state_2_),
	.A(FE_PHN139_core_I_2_state_2_));
   DLY4X4 FE_PHC138_core_I_1_regLoad_0_ (.Y(FE_PHN200_core_I_1_regLoad_0_),
	.A(FE_PHN108_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC137_core_I_2_state_0_ (.Y(FE_PHN137_core_I_2_state_0_),
	.A(FE_PHN43_core_I_2_state_0_));
   DLY4X4 FE_PHC136_core_I_2_state_3_ (.Y(FE_PHN136_core_I_2_state_3_),
	.A(FE_PHN77_core_I_2_state_3_));
   DLY4X4 FE_PHC135_core_I_2_state_1_ (.Y(FE_PHN135_core_I_2_state_1_),
	.A(FE_PHN251_core_I_2_state_1_));
   DLY4X4 FE_PHC134_core_I_1_regLoad_1_ (.Y(FE_PHN167_core_I_1_regLoad_1_),
	.A(FE_PHN104_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC133_core_I_1_regAdd_4_ (.Y(FE_PHN133_core_I_1_regAdd_4_),
	.A(FE_PHN46_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC132_core_I_1_regAdd_3_ (.Y(FE_PHN132_core_I_1_regAdd_3_),
	.A(FE_PHN51_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC131_core_I_1_regAdd_2_ (.Y(FE_PHN131_core_I_1_regAdd_2_),
	.A(FE_PHN71_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC130_n60 (.Y(FE_PHN130_n60),
	.A(FE_PHN322_n60));
   DLY4X4 FE_PHC129_n50 (.Y(FE_PHN129_n50),
	.A(FE_PHN34_n50));
   DLY4X4 FE_PHC128_n52 (.Y(FE_PHN128_n52),
	.A(FE_PHN28_n52));
   DLY4X4 FE_PHC127_n51 (.Y(FE_PHN127_n51),
	.A(FE_PHN35_n51));
   DLY4X4 FE_PHC126_n65 (.Y(FE_PHN126_n65),
	.A(FE_PHN36_n65));
   DLY4X4 FE_PHC125_n53 (.Y(FE_PHN125_n53),
	.A(FE_PHN31_n53));
   DLY4X4 FE_PHC124_n58 (.Y(FE_PHN93_n58),
	.A(FE_PHN124_n58));
   DLY4X4 FE_PHC123_n59 (.Y(FE_PHN232_n59),
	.A(FE_PHN123_n59));
   DLY4X4 FE_PHC122_n48 (.Y(FE_PHN122_n48),
	.A(FE_PHN208_n48));
   DLY4X4 FE_PHC121_FE_OFN0_s_cardReady (.Y(FE_PHN121_FE_OFN0_s_cardReady),
	.A(FE_PHN100_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC120_n55 (.Y(FE_PHN120_n55),
	.A(FE_PHN52_n55));
   DLY4X4 FE_PHC119_n57 (.Y(FE_PHN119_n57),
	.A(FE_PHN89_n57));
   DLY4X4 FE_PHC118_n61 (.Y(FE_PHN118_n61),
	.A(FE_PHN91_n61));
   DLY4X4 FE_PHC117_n54 (.Y(FE_PHN117_n54),
	.A(FE_PHN95_n54));
   DLY4X4 FE_PHC116_n49 (.Y(FE_PHN116_n49),
	.A(FE_PHN97_n49));
   DLY4X4 FE_PHC115_n66 (.Y(FE_PHN115_n66),
	.A(FE_PHN56_n66));
   DLY4X4 FE_PHC114_n63 (.Y(FE_PHN114_n63),
	.A(FE_PHN90_n63));
   DLY4X4 FE_PHC113_n64 (.Y(FE_PHN113_n64),
	.A(FE_PHN96_n64));
   DLY4X4 FE_PHC112_FE_OFN1_s_start (.Y(FE_PHN112_FE_OFN1_s_start),
	.A(FE_PHN437_FE_OFN1_s_start));
   DLY4X4 FE_PHC111_core_I_1_regAdd_1_ (.Y(FE_PHN111_core_I_1_regAdd_1_),
	.A(FE_PHN201_core_I_1_regAdd_1_));
   DLY4X1 FE_PHC110_core_I_2_state_2_ (.Y(FE_PHN197_core_I_2_state_2_),
	.A(FE_PHN42_core_I_2_state_2_));
   DLY4X4 FE_PHC109_core_I_1_regAdd_0_ (.Y(FE_PHN109_core_I_1_regAdd_0_),
	.A(FE_PHN199_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC108_core_I_1_regLoad_0_ (.Y(FE_PHN108_core_I_1_regLoad_0_),
	.A(FE_PHN80_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC107_core_I_2_state_3_ (.Y(FE_PHN107_core_I_2_state_3_),
	.A(FE_PHN136_core_I_2_state_3_));
   DLY4X4 FE_PHC106_core_I_2_state_1_ (.Y(FE_PHN106_core_I_2_state_1_),
	.A(FE_PHN224_core_I_2_state_1_));
   DLY4X4 FE_PHC105_core_I_2_state_0_ (.Y(FE_PHN105_core_I_2_state_0_),
	.A(FE_PHN74_core_I_2_state_0_));
   DLY4X4 FE_PHC104_core_I_1_regLoad_1_ (.Y(FE_PHN104_core_I_1_regLoad_1_),
	.A(FE_PHN48_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC103_core_I_1_regAdd_4_ (.Y(FE_PHN103_core_I_1_regAdd_4_),
	.A(FE_PHN333_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC102_core_I_1_regAdd_2_ (.Y(FE_PHN102_core_I_1_regAdd_2_),
	.A(FE_PHN191_core_I_1_regAdd_2_));
   DLY4X4 FE_PHC101_core_I_1_regAdd_3_ (.Y(FE_PHN101_core_I_1_regAdd_3_),
	.A(FE_PHN72_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC100_FE_OFN0_s_cardReady (.Y(FE_PHN100_FE_OFN0_s_cardReady),
	.A(FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC99_FE_OFN1_s_start (.Y(FE_PHN99_FE_OFN1_s_start),
	.A(FE_PHN68_FE_OFN1_s_start));
   DLY4X4 FE_PHC98_n60 (.Y(FE_PHN98_n60),
	.A(FE_PHN69_n60));
   DLY4X4 FE_PHC97_n49 (.Y(FE_PHN97_n49),
	.A(FE_PHN272_n49));
   DLY4X4 FE_PHC96_n64 (.Y(FE_PHN96_n64),
	.A(FE_PHN60_n64));
   DLY4X4 FE_PHC95_n54 (.Y(FE_PHN95_n54),
	.A(FE_PHN32_n54));
   DLY4X4 FE_PHC94_n59 (.Y(FE_PHN154_n59),
	.A(FE_PHN25_n59));
   DLY4X4 FE_PHC93_n58 (.Y(FE_PHN151_n58),
	.A(FE_PHN39_n58));
   DLY4X4 FE_PHC92_n66 (.Y(FE_PHN92_n66),
	.A(FE_PHN261_n66));
   DLY4X4 FE_PHC91_n61 (.Y(FE_PHN91_n61),
	.A(FE_PHN177_n61));
   DLY4X4 FE_PHC90_n63 (.Y(FE_PHN90_n63),
	.A(FE_PHN29_n63));
   DLY4X4 FE_PHC89_n57 (.Y(FE_PHN89_n57),
	.A(FE_PHN53_n57));
   DLY4X4 FE_PHC88_n55 (.Y(FE_PHN88_n55),
	.A(FE_PHN287_n55));
   DLY4X4 FE_PHC87_n52 (.Y(FE_PHN87_n52),
	.A(FE_PHN206_n52));
   DLY4X4 FE_PHC86_n51 (.Y(FE_PHN86_n51),
	.A(FE_PHN65_n51));
   DLY4X4 FE_PHC85_n48 (.Y(FE_PHN85_n48),
	.A(FE_PHN66_n48));
   DLY4X4 FE_PHC84_n50 (.Y(FE_PHN84_n50),
	.A(FE_PHN296_n50));
   DLY4X4 FE_PHC83_n65 (.Y(FE_PHN83_n65),
	.A(FE_PHN64_n65));
   DLY4X4 FE_PHC82_n53 (.Y(FE_PHN82_n53),
	.A(FE_PHN275_n53));
   DLY4X4 FE_PHC81_core_I_1_regAdd_1_ (.Y(FE_PHN81_core_I_1_regAdd_1_),
	.A(FE_PHN47_core_I_1_regAdd_1_));
   DLY4X4 FE_PHC80_core_I_1_regLoad_0_ (.Y(FE_PHN80_core_I_1_regLoad_0_),
	.A(FE_PHN49_core_I_1_regLoad_0_));
   DLY4X4 FE_PHC79_core_I_1_regAdd_0_ (.Y(FE_PHN79_core_I_1_regAdd_0_),
	.A(FE_PHN50_core_I_1_regAdd_0_));
   DLY4X4 FE_PHC78_core_I_1_regLoad_1_ (.Y(FE_PHN78_core_I_1_regLoad_1_),
	.A(FE_PHN134_core_I_1_regLoad_1_));
   DLY4X4 FE_PHC77_core_I_2_state_3_ (.Y(FE_PHN77_core_I_2_state_3_),
	.A(FE_PHN41_core_I_2_state_3_));
   DLY4X4 FE_PHC76_core_I_2_state_1_ (.Y(FE_PHN76_core_I_2_state_1_),
	.A(FE_PHN307_core_I_2_state_1_));
   DLY4X4 FE_PHC75_core_I_2_state_2_ (.Y(FE_PHN75_core_I_2_state_2_),
	.A(FE_PHN110_core_I_2_state_2_));
   DLY4X4 FE_PHC74_core_I_2_state_0_ (.Y(FE_PHN74_core_I_2_state_0_),
	.A(FE_PHN278_core_I_2_state_0_));
   DLY4X4 FE_PHC73_core_I_1_regAdd_4_ (.Y(FE_PHN73_core_I_1_regAdd_4_),
	.A(FE_PHN163_core_I_1_regAdd_4_));
   DLY4X4 FE_PHC72_core_I_1_regAdd_3_ (.Y(FE_PHN72_core_I_1_regAdd_3_),
	.A(FE_PHN192_core_I_1_regAdd_3_));
   DLY4X4 FE_PHC71_core_I_1_regAdd_2_ (.Y(FE_PHN71_core_I_1_regAdd_2_),
	.A(FE_PHN45_core_I_1_regAdd_2_));
   DLY4X1 FE_PHC70_FE_OFN0_s_cardReady (.Y(FE_PHN70_FE_OFN0_s_cardReady),
	.A(FE_PHN185_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC69_n60 (.Y(FE_PHN69_n60),
	.A(n60));
   DLY4X1 FE_PHC68_FE_OFN1_s_start (.Y(FE_OFN1_s_start),
	.A(FE_PHN231_FE_OFN1_s_start));
   DLY4X4 FE_PHC67_n59 (.Y(FE_PHN67_n59),
	.A(FE_PHN94_n59));
   DLY4X4 FE_PHC66_n48 (.Y(FE_PHN66_n48),
	.A(FE_PHN33_n48));
   DLY4X4 FE_PHC65_n51 (.Y(FE_PHN65_n51),
	.A(FE_PHN291_n51));
   DLY4X4 FE_PHC64_n65 (.Y(FE_PHN64_n65),
	.A(FE_PHN179_n65));
   DLY4X4 FE_PHC63_n53 (.Y(FE_PHN63_n53),
	.A(FE_PHN152_n53));
   DLY4X4 FE_PHC62_n49 (.Y(FE_PHN62_n49),
	.A(FE_PHN205_n49));
   DLY4X4 FE_PHC61_n58 (.Y(FE_PHN61_n58),
	.A(FE_PHN93_n58));
   DLY4X4 FE_PHC60_n64 (.Y(FE_PHN60_n64),
	.A(FE_PHN37_n64));
   DLY4X4 FE_PHC59_n61 (.Y(FE_PHN59_n61),
	.A(FE_PHN118_n61));
   DLY4X4 FE_PHC58_n52 (.Y(FE_PHN58_n52),
	.A(FE_PHN175_n52));
   DLY4X4 FE_PHC57_n63 (.Y(FE_PHN57_n63),
	.A(FE_PHN181_n63));
   DLY4X4 FE_PHC56_n66 (.Y(FE_PHN56_n66),
	.A(FE_PHN40_n66));
   DLY4X4 FE_PHC55_n54 (.Y(FE_PHN55_n54),
	.A(FE_PHN187_n54));
   DLY4X4 FE_PHC54_n50 (.Y(FE_PHN54_n50),
	.A(FE_PHN207_n50));
   DLY4X4 FE_PHC53_n57 (.Y(FE_PHN53_n57),
	.A(FE_PHN24_n57));
   DLY4X4 FE_PHC52_n55 (.Y(FE_PHN52_n55),
	.A(FE_PHN27_n55));
   DLY4X4 FE_PHC51_core_I_1_regAdd_3_ (.Y(FE_PHN51_core_I_1_regAdd_3_),
	.A(\core/I_1/regAdd [3]));
   DLY4X4 FE_PHC50_core_I_1_regAdd_0_ (.Y(FE_PHN50_core_I_1_regAdd_0_),
	.A(\core/I_1/regAdd [0]));
   DLY4X4 FE_PHC49_core_I_1_regLoad_0_ (.Y(FE_PHN49_core_I_1_regLoad_0_),
	.A(\core/I_1/regLoad [0]));
   DLY4X4 FE_PHC48_core_I_1_regLoad_1_ (.Y(FE_PHN48_core_I_1_regLoad_1_),
	.A(\core/I_1/regLoad [1]));
   DLY4X4 FE_PHC47_core_I_1_regAdd_1_ (.Y(FE_PHN47_core_I_1_regAdd_1_),
	.A(\core/I_1/regAdd [1]));
   DLY4X4 FE_PHC46_core_I_1_regAdd_4_ (.Y(FE_PHN46_core_I_1_regAdd_4_),
	.A(\core/I_1/regAdd [4]));
   DLY4X4 FE_PHC45_core_I_1_regAdd_2_ (.Y(FE_PHN45_core_I_1_regAdd_2_),
	.A(\core/I_1/regAdd [2]));
   DLY4X4 FE_PHC44_core_I_2_state_1_ (.Y(FE_PHN44_core_I_2_state_1_),
	.A(\core/I_2/state [1]));
   DLY4X4 FE_PHC43_core_I_2_state_0_ (.Y(FE_PHN43_core_I_2_state_0_),
	.A(\core/I_2/state [0]));
   DLY4X4 FE_PHC42_core_I_2_state_2_ (.Y(FE_PHN42_core_I_2_state_2_),
	.A(\core/I_2/state [2]));
   DLY4X4 FE_PHC41_core_I_2_state_3_ (.Y(FE_PHN41_core_I_2_state_3_),
	.A(\core/I_2/state [3]));
   DLY4X4 FE_PHC40_n66 (.Y(FE_PHN40_n66),
	.A(n66));
   DLY4X4 FE_PHC39_n58 (.Y(FE_PHN39_n58),
	.A(n58));
   DLY4X4 FE_PHC38_FE_OFN0_s_cardReady (.Y(FE_PHN38_FE_OFN0_s_cardReady),
	.A(FE_PHN70_FE_OFN0_s_cardReady));
   DLY4X4 FE_PHC37_n64 (.Y(FE_PHN37_n64),
	.A(n64));
   DLY4X4 FE_PHC36_n65 (.Y(FE_PHN36_n65),
	.A(n65));
   DLY4X4 FE_PHC35_n51 (.Y(FE_PHN35_n51),
	.A(n51));
   DLY4X4 FE_PHC34_n50 (.Y(FE_PHN34_n50),
	.A(n50));
   DLY4X4 FE_PHC33_n48 (.Y(FE_PHN33_n48),
	.A(n48));
   DLY4X4 FE_PHC32_n54 (.Y(FE_PHN32_n54),
	.A(n54));
   DLY4X4 FE_PHC31_n53 (.Y(FE_PHN31_n53),
	.A(n53));
   DLY4X4 FE_PHC30_n49 (.Y(FE_PHN30_n49),
	.A(n49));
   DLY4X4 FE_PHC29_n63 (.Y(FE_PHN29_n63),
	.A(n63));
   DLY4X4 FE_PHC28_n52 (.Y(FE_PHN28_n52),
	.A(n52));
   DLY4X4 FE_PHC27_n55 (.Y(FE_PHN27_n55),
	.A(n55));
   DLY4X4 FE_PHC26_n61 (.Y(FE_PHN26_n61),
	.A(n61));
   DLY4X4 FE_PHC25_n59 (.Y(FE_PHN25_n59),
	.A(n59));
   DLY4X4 FE_PHC24_n57 (.Y(FE_PHN24_n57),
	.A(n57));
   DLY4X4 FE_PHC23_FE_OFN1_s_start (.Y(FE_PHN23_FE_OFN1_s_start),
	.A(FE_OFN1_s_start));
   DLY4X1 FE_PHC22_core_I_1_regAdd_3_ (.Y(FE_PHN22_core_I_1_regAdd_3_),
	.A(FE_PHN332_core_I_1_regAdd_3_));
   DLY4X1 FE_PHC21_core_I_1_regLoad_0_ (.Y(FE_PHN21_core_I_1_regLoad_0_),
	.A(FE_PHN138_core_I_1_regLoad_0_));
   DLY4X1 FE_PHC20_core_I_1_regAdd_0_ (.Y(FE_PHN20_core_I_1_regAdd_0_),
	.A(FE_PHN109_core_I_1_regAdd_0_));
   DLY4X1 FE_PHC19_core_I_1_regLoad_1_ (.Y(FE_PHN19_core_I_1_regLoad_1_),
	.A(FE_PHN78_core_I_1_regLoad_1_));
   DLY4X1 FE_PHC18_core_I_2_state_1_ (.Y(FE_PHN18_core_I_2_state_1_),
	.A(FE_PHN282_core_I_2_state_1_));
   DLY4X1 FE_PHC17_core_I_1_regAdd_4_ (.Y(FE_PHN17_core_I_1_regAdd_4_),
	.A(FE_PHN193_core_I_1_regAdd_4_));
   DLY4X1 FE_PHC16_core_I_1_regAdd_2_ (.Y(FE_PHN16_core_I_1_regAdd_2_),
	.A(FE_PHN102_core_I_1_regAdd_2_));
   DLY4X1 FE_PHC15_core_I_1_regAdd_1_ (.Y(FE_PHN15_core_I_1_regAdd_1_),
	.A(FE_PHN111_core_I_1_regAdd_1_));
   DLY4X1 FE_PHC14_core_I_2_state_0_ (.Y(FE_PHN14_core_I_2_state_0_),
	.A(FE_PHN105_core_I_2_state_0_));
   DLY4X1 FE_PHC13_core_I_2_state_2_ (.Y(FE_PHN13_core_I_2_state_2_),
	.A(FE_PHN75_core_I_2_state_2_));
   DLY4X1 FE_PHC12_core_I_2_state_3_ (.Y(FE_PHN12_core_I_2_state_3_),
	.A(FE_PHN165_core_I_2_state_3_));
   CLKBUFX2 FE_OFC11_n67 (.Y(FE_OFN11_n67),
	.A(n67));
   CLKBUFX6 FE_OFC10_s_score_3_ (.Y(FE_OFN10_s_score_3_),
	.A(FE_PHN398_s_score_3_));
   CLKBUFX6 FE_OFC9_s_score_4_ (.Y(FE_OFN9_s_score_4_),
	.A(FE_PHN414_s_score_4_));
   CLKBUFX6 FE_OFC8_s_score_2_ (.Y(FE_OFN8_s_score_2_),
	.A(FE_PHN399_s_score_2_));
   CLKBUFX16 FE_OFC7_s_score_0_ (.Y(FE_OFN7_s_score_0_),
	.A(FE_PHN349_s_score_0_));
   CLKBUFX6 FE_OFC6_s_score_1_ (.Y(FE_OFN6_s_score_1_),
	.A(FE_PHN363_s_score_1_));
   CLKBUFX3 FE_OFC5_s_cardValue_0_ (.Y(FE_OFN5_s_cardValue_0_),
	.A(s_cardValue[0]));
   CLKBUFX3 FE_OFC4_s_cardValue_1_ (.Y(FE_OFN4_s_cardValue_1_),
	.A(s_cardValue[1]));
   CLKBUFX2 FE_OFC3_s_cardValue_2_ (.Y(FE_OFN3_s_cardValue_2_),
	.A(s_cardValue[2]));
   CLKBUFX2 FE_OFC2_s_cardValue_3_ (.Y(FE_OFN2_s_cardValue_3_),
	.A(s_cardValue[3]));
   CLKBUFX4 FE_OFC1_s_start (.Y(FE_PHN68_FE_OFN1_s_start),
	.A(s_start));
   CLKBUFX2 FE_OFC0_s_cardReady (.Y(FE_OFN0_s_cardReady),
	.A(s_cardReady));
   PADDO IO_LOST (.PAD(lost),
	.A(s_lost));
   PADDO IO_FINISHED (.PAD(finished),
	.A(FE_OFN11_n67));
   PADDO IO_NEWCARD (.PAD(newCard),
	.A(n68));
   PADDO IO_SCORE_0 (.PAD(score[0]),
	.A(FE_OFN7_s_score_0_));
   PADDO IO_SCORE_1 (.PAD(score[1]),
	.A(FE_OFN6_s_score_1_));
   PADDO IO_SCORE_2 (.PAD(score[2]),
	.A(FE_OFN8_s_score_2_));
   PADDO IO_SCORE_3 (.PAD(score[3]),
	.A(FE_OFN10_s_score_3_));
   PADDO IO_SCORE_4 (.PAD(score[4]),
	.A(FE_OFN9_s_score_4_));
   PADDI IO_CARDREADY (.Y(s_cardReady),
	.PAD(cardReady));
   PADDI IO_START (.Y(s_start),
	.PAD(start));
   PADDI IO_CARDVALUE_0 (.Y(s_cardValue[0]),
	.PAD(cardValue[0]));
   PADDI IO_CARDVALUE_1 (.Y(s_cardValue[1]),
	.PAD(cardValue[1]));
   PADDI IO_CARDVALUE_2 (.Y(s_cardValue[2]),
	.PAD(cardValue[2]));
   PADDI IO_CARDVALUE_3 (.Y(s_cardValue[3]),
	.PAD(cardValue[3]));
   PADDI IO_CLK (.Y(s_clk),
	.PAD(clk));
   DFFRHQX1 \core/I_2/cardReadySync_reg  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_2/cardReadySync ),
	.D(FE_PHN38_FE_OFN0_s_cardReady),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regAdd_reg[0]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regAdd [0]),
	.D(FE_PHN368_n62),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regAdd_reg[3]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regAdd [3]),
	.D(FE_PHN143_n54),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regLoad_reg[0]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regLoad [0]),
	.D(FE_PHN209_n57),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regLoad_reg[3]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regLoad [3]),
	.D(FE_PHN67_n59),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regLoad_reg[1]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regLoad [1]),
	.D(FE_PHN59_n61),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regLoad_reg[4]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regLoad [4]),
	.D(FE_PHN61_n58),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/score_reg[1]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(s_score[1]),
	.D(FE_PHN260_n52),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/score_reg[2]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(s_score[2]),
	.D(FE_PHN314_n51),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/score_reg[3]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(s_score[3]),
	.D(FE_PHN234_n50),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/score_reg[4]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(s_score[4]),
	.D(FE_PHN236_n49),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/score_reg[0]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(s_score[0]),
	.D(FE_PHN122_n48),
	.CK(s_clk));
   DFFRHQX4 \core/I_2/state_reg[3]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_2/state [3]),
	.D(FE_PHN147_n66),
	.CK(s_clk));
   DFFRHQX2 \core/I_1/regAdd_reg[4]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regAdd [4]),
	.D(FE_PHN203_n53),
	.CK(s_clk));
   DFFRHQX2 \core/I_1/regAdd_reg[1]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regAdd [1]),
	.D(FE_PHN369_n56),
	.CK(s_clk));
   DFFRHQX4 \core/I_2/state_reg[2]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_2/state [2]),
	.D(FE_PHN57_n63),
	.CK(s_clk));
   DFFRHQX2 \core/I_2/state_reg[0]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_2/state [0]),
	.D(FE_PHN83_n65),
	.CK(s_clk));
   DFFRHQX1 \core/I_1/regLoad_reg[2]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regLoad [2]),
	.D(FE_PHN130_n60),
	.CK(s_clk));
   DFFRHQX2 \core/I_2/state_reg[1]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_2/state [1]),
	.D(FE_PHN153_n64),
	.CK(s_clk));
   DFFRHQX2 \core/I_1/regAdd_reg[2]  (.RN(FE_PHN23_FE_OFN1_s_start),
	.Q(\core/I_1/regAdd [2]),
	.D(FE_PHN88_n55),
	.CK(s_clk));
   OAI2BB1XL U71 (.Y(n77),
	.B0(FE_PHN13_core_I_2_state_2_),
	.A1N(n76),
	.A0N(n110));
   OAI221X2 U72 (.Y(n122),
	.C0(n130),
	.B1(FE_PHN337_core_I_1_regLoad_2_),
	.B0(n123),
	.A1(n120),
	.A0(n121));
   NOR2X2 U73 (.Y(n92),
	.B(FE_PHN13_core_I_2_state_2_),
	.A(n106));
   AOI32X1 U74 (.Y(n71),
	.B1(FE_PHN12_core_I_2_state_3_),
	.B0(n84),
	.A2(n96),
	.A1(FE_PHN12_core_I_2_state_3_),
	.A0(n80));
   MX2XL U75 (.Y(n49),
	.S0(n133),
	.B(FE_OFN9_s_score_4_),
	.A(FE_PHN17_core_I_1_regAdd_4_));
   MX2XL U76 (.Y(n52),
	.S0(n133),
	.B(FE_OFN6_s_score_1_),
	.A(FE_PHN15_core_I_1_regAdd_1_));
   OAI211X2 U77 (.Y(n107),
	.C0(n79),
	.B0(n92),
	.A1(n80),
	.A0(FE_PHN12_core_I_2_state_3_));
   NOR2X2 U78 (.Y(n80),
	.B(n70),
	.A(FE_PHN337_core_I_1_regLoad_2_));
   XNOR2X1 U79 (.Y(n55),
	.B(n122),
	.A(FE_PHN16_core_I_1_regAdd_2_));
   OAI222X2 U80 (.Y(n131),
	.C1(n127),
	.C0(n126),
	.B1(n126),
	.B0(n128),
	.A1(n127),
	.A0(n128));
   NOR3X2 U81 (.Y(n100),
	.C(n87),
	.B(n97),
	.A(n75));
   INVX2 U82 (.Y(n106),
	.A(FE_PHN18_core_I_2_state_1_));
   INVX2 U83 (.Y(n96),
	.A(FE_PHN14_core_I_2_state_0_));
   AOI211X4 U84 (.Y(n114),
	.C0(n115),
	.B0(n91),
	.A1(n92),
	.A0(FE_PHN14_core_I_2_state_0_));
   NAND2X2 U85 (.Y(n113),
	.B(n94),
	.A(n90));
   OAI21X1 U86 (.Y(n90),
	.B0(FE_PHN12_core_I_2_state_3_),
	.A1(n81),
	.A0(n91));
   NAND2X2 U87 (.Y(n109),
	.B(FE_PHN14_core_I_2_state_0_),
	.A(FE_PHN13_core_I_2_state_2_));
   XNOR2X1 U88 (.Y(n56),
	.B(n117),
	.A(FE_PHN15_core_I_1_regAdd_1_));
   XNOR2X1 U89 (.Y(n53),
	.B(n132),
	.A(FE_PHN17_core_I_1_regAdd_4_));
   AOI32X2 U90 (.Y(n76),
	.B1(FE_PHN17_core_I_1_regAdd_4_),
	.B0(n74),
	.A2(FE_PHN15_core_I_1_regAdd_1_),
	.A1(FE_PHN17_core_I_1_regAdd_4_),
	.A0(FE_PHN20_core_I_1_regAdd_0_));
   OAI211X2 U91 (.Y(n73),
	.C0(FE_PHN17_core_I_1_regAdd_4_),
	.B0(n74),
	.A1(FE_PHN15_core_I_1_regAdd_1_),
	.A0(FE_PHN22_core_I_1_regAdd_3_));
   OAI31X2 U92 (.Y(n87),
	.B0(FE_PHN17_core_I_1_regAdd_4_),
	.A2(n74),
	.A1(FE_PHN15_core_I_1_regAdd_1_),
	.A0(FE_PHN20_core_I_1_regAdd_0_));
   OAI222X4 U93 (.Y(n128),
	.C1(FE_PHN337_core_I_1_regLoad_2_),
	.C0(n123),
	.B1(n123),
	.B0(FE_PHN16_core_I_1_regAdd_2_),
	.A1(FE_PHN337_core_I_1_regLoad_2_),
	.A0(FE_PHN16_core_I_1_regAdd_2_));
   OAI2BB1X2 U94 (.Y(n123),
	.B0(n118),
	.A1N(n119),
	.A0N(FE_PHN15_core_I_1_regAdd_1_));
   NOR2X4 U95 (.Y(n95),
	.B(FE_PHN12_core_I_2_state_3_),
	.A(FE_PHN14_core_I_2_state_0_));
   AOI211X4 U96 (.Y(n130),
	.C0(n84),
	.B0(n95),
	.A1(FE_PHN12_core_I_2_state_3_),
	.A0(FE_PHN14_core_I_2_state_0_));
   OAI211X2 U97 (.Y(n102),
	.C0(FE_PHN14_core_I_2_state_0_),
	.B0(FE_PHN13_core_I_2_state_2_),
	.A1(n106),
	.A0(FE_PHN12_core_I_2_state_3_));
   OAI211XL U98 (.Y(n101),
	.C0(FE_PHN12_core_I_2_state_3_),
	.B0(FE_PHN18_core_I_2_state_1_),
	.A1(FE_PHN14_core_I_2_state_0_),
	.A0(FE_PHN13_core_I_2_state_2_));
   OAI211XL U99 (.Y(n104),
	.C0(n101),
	.B0(n102),
	.A1(n103),
	.A0(FE_PHN13_core_I_2_state_2_));
   INVXL U100 (.Y(n75),
	.A(n73));
   AOI21XL U101 (.Y(n108),
	.B0(n104),
	.A1(n105),
	.A0(n106));
   NOR2X6 U102 (.Y(s_lost),
	.B(n109),
	.A(\core/I_2/state [1]));
   INVX1 U103 (.Y(n98),
	.A(FE_PHN367_core_I_2_cardReadySync));
   OR2X1 U104 (.Y(n74),
	.B(FE_PHN22_core_I_1_regAdd_3_),
	.A(FE_PHN16_core_I_1_regAdd_2_));
   NAND2BX1 U105 (.Y(n86),
	.B(n73),
	.AN(n76));
   NAND4BX1 U106 (.Y(n72),
	.D(n86),
	.C(n98),
	.B(FE_PHN18_core_I_2_state_1_),
	.AN(n109));
   INVXL U107 (.Y(n93),
	.A(FE_PHN335_core_I_1_regLoad_4_));
   NAND4X2 U108 (.Y(n70),
	.D(n93),
	.C(FE_PHN336_core_I_1_regLoad_3_),
	.B(FE_PHN19_core_I_1_regLoad_1_),
	.A(FE_PHN21_core_I_1_regLoad_0_));
   INVXL U109 (.Y(n84),
	.A(n92));
   NAND2XL U110 (.Y(n66),
	.B(n71),
	.A(n72));
   INVX1 U111 (.Y(n97),
	.A(FE_PHN13_core_I_2_state_2_));
   NOR2X1 U112 (.Y(n110),
	.B(FE_PHN367_core_I_2_cardReadySync),
	.A(n75));
   AOI211X1 U113 (.Y(n78),
	.C0(n106),
	.B0(FE_PHN12_core_I_2_state_3_),
	.A1(n77),
	.A0(FE_PHN14_core_I_2_state_0_));
   AOI31X1 U114 (.Y(n83),
	.B0(n78),
	.A2(n98),
	.A1(n100),
	.A0(n95));
   NAND2XL U115 (.Y(n79),
	.B(n80),
	.A(FE_PHN12_core_I_2_state_3_));
   NAND2X1 U116 (.Y(n85),
	.B(n96),
	.A(FE_PHN13_core_I_2_state_2_));
   NOR2X1 U117 (.Y(n91),
	.B(n85),
	.A(FE_PHN18_core_I_2_state_1_));
   NOR2XL U118 (.Y(n81),
	.B(n96),
	.A(FE_PHN13_core_I_2_state_2_));
   NAND4X2 U119 (.Y(n82),
	.D(n106),
	.C(n97),
	.B(FE_PHN367_core_I_2_cardReadySync),
	.A(FE_PHN14_core_I_2_state_0_));
   NAND4X1 U120 (.Y(n64),
	.D(n82),
	.C(n90),
	.B(n107),
	.A(n83));
   OR2X2 U121 (.Y(n133),
	.B(n106),
	.A(n85));
   INVXL U122 (.Y(n103),
	.A(n95));
   OAI222X1 U123 (.Y(n88),
	.C1(n86),
	.C0(n96),
	.B1(FE_PHN12_core_I_2_state_3_),
	.B0(n98),
	.A1(n87),
	.A0(n103));
   NAND2XL U124 (.Y(n89),
	.B(FE_PHN386_n88),
	.A(FE_PHN13_core_I_2_state_2_));
   NAND4BX1 U125 (.Y(n63),
	.D(n89),
	.C(n133),
	.B(n102),
	.AN(n130));
   NAND2X1 U126 (.Y(n94),
	.B(n95),
	.A(n92));
   INVX1 U127 (.Y(n115),
	.A(n113));
   AOI21XL U128 (.Y(n58),
	.B0(n114),
	.A1(FE_PHN501_n93),
	.A0(n115));
   NAND2BX4 U129 (.Y(n67),
	.B(n133),
	.AN(s_lost));
   OAI31X4 U130 (.Y(n68),
	.B0(n94),
	.A2(n95),
	.A1(\core/I_2/state [1]),
	.A0(\core/I_2/state [2]));
   NAND2XL U131 (.Y(n99),
	.B(n96),
	.A(n97));
   OAI32X1 U132 (.Y(n105),
	.B1(n98),
	.B0(n99),
	.A2(n100),
	.A1(FE_PHN12_core_I_2_state_3_),
	.A0(FE_PHN367_core_I_2_cardReadySync));
   OAI211XL U133 (.Y(n65),
	.C0(n107),
	.B0(n108),
	.A1(n109),
	.A0(n110));
   NAND2XL U134 (.Y(n111),
	.B(n130),
	.A(FE_PHN21_core_I_1_regLoad_0_));
   XNOR2X1 U135 (.Y(n62),
	.B(n111),
	.A(FE_PHN20_core_I_1_regAdd_0_));
   INVXL U136 (.Y(n112),
	.A(n114));
   OA22X1 U137 (.Y(n61),
	.B1(n112),
	.B0(FE_PHN353_FE_OFN4_s_cardValue_1_),
	.A1(n113),
	.A0(FE_PHN19_core_I_1_regLoad_1_));
   OA22X1 U138 (.Y(n60),
	.B1(n112),
	.B0(FE_PHN355_FE_OFN3_s_cardValue_2_),
	.A1(n113),
	.A0(FE_PHN524_core_I_1_regLoad_2_));
   AO22XL U139 (.Y(n59),
	.B1(FE_PHN352_FE_OFN2_s_cardValue_3_),
	.B0(n114),
	.A1(n115),
	.A0(FE_PHN336_core_I_1_regLoad_3_));
   AO22XL U140 (.Y(n57),
	.B1(FE_PHN354_FE_OFN5_s_cardValue_0_),
	.B0(n114),
	.A1(n115),
	.A0(FE_PHN21_core_I_1_regLoad_0_));
   NAND2X1 U141 (.Y(n116),
	.B(FE_PHN21_core_I_1_regLoad_0_),
	.A(FE_PHN20_core_I_1_regAdd_0_));
   NAND2BX1 U142 (.Y(n118),
	.B(FE_PHN19_core_I_1_regLoad_1_),
	.AN(n116));
   NAND2BX1 U143 (.Y(n119),
	.B(n116),
	.AN(FE_PHN19_core_I_1_regLoad_1_));
   NAND3XL U144 (.Y(n117),
	.C(n119),
	.B(n118),
	.A(n130));
   INVXL U145 (.Y(n121),
	.A(n123));
   INVXL U146 (.Y(n120),
	.A(FE_PHN337_core_I_1_regLoad_2_));
   INVX1 U147 (.Y(n126),
	.A(FE_PHN336_core_I_1_regLoad_3_));
   INVXL U148 (.Y(n124),
	.A(n128));
   OAI221X1 U149 (.Y(n125),
	.C0(n130),
	.B1(FE_PHN336_core_I_1_regLoad_3_),
	.B0(n124),
	.A1(n126),
	.A0(n128));
   XNOR2X1 U150 (.Y(n54),
	.B(n125),
	.A(FE_PHN22_core_I_1_regAdd_3_));
   INVXL U151 (.Y(n127),
	.A(FE_PHN22_core_I_1_regAdd_3_));
   NAND2XL U152 (.Y(n129),
	.B(n131),
	.A(FE_PHN335_core_I_1_regLoad_4_));
   OAI211X1 U153 (.Y(n132),
	.C0(n129),
	.B0(n130),
	.A1(n131),
	.A0(FE_PHN335_core_I_1_regLoad_4_));
   MX2XL U154 (.Y(n51),
	.S0(n133),
	.B(FE_OFN8_s_score_2_),
	.A(FE_PHN16_core_I_1_regAdd_2_));
   MX2XL U155 (.Y(n50),
	.S0(n133),
	.B(FE_OFN10_s_score_3_),
	.A(FE_PHN22_core_I_1_regAdd_3_));
   MX2XL U156 (.Y(n48),
	.S0(n133),
	.B(FE_OFN7_s_score_0_),
	.A(FE_PHN20_core_I_1_regAdd_0_));
endmodule

